force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectProduct__c/ProjectProduct__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>ProjProd{000000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectProduct__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/projectProductHandler.cls
/*****************************************************************************************************************************
Author:sanhita.hegde
Description: Helps ProductRestriction trigger
name :OppTeamMemberTriggerHelper 
****************************************************************************************************************************/
public with sharing class projectProductHandler{
    Private List<ProjectProduct__c > newOppList = new List<ProjectProduct__c >();
    Private static final string ERRORMSG = 'You can only add Products from the Opportunity as a Project Product';
    /*****************************************************************************************************************************
Author:sanhita.hegde
Description: Helps MasterOpp trigger
name :OppTeamMemberTriggerHelper 
****************************************************************************************************************************/
    public projectProductHandler( List<ProjectProduct__c > newTriggerList){
        newOppList = newTriggerList ;
    }
    /*****************************************************************************************************************************
Author:sanhita.hegde
Description: It will add the members to the realted project team when opportunity member gets added.
name :addProjectTeam 
****************************************************************************************************************************/
    public void restrictionProduct(){
        List<Id> projectIds = new List<Id>();
        For(ProjectProduct__c pp:newOppList ){
            projectIds.add(pp.Project__c);
        }
        List<Id> holdOppId = new List<Id>();
        for(Project__c p: [select Opportunity__c from Project__c where Id In: projectIds]){
            holdOppId.add(p.Opportunity__c);
        }
        
        Set<Id> listSet = new Set<Id>();
        for(OpportunityLineItem op: [select Product2Id from OpportunityLineItem where OpportunityId In: holdOppId]){
            listSet.add(op.Product2Id);
            
        }
        
        For(ProjectProduct__c pp:newOppList){
            If(listSet.Contains(pp.Product__c)){
            }
            else{
                pp.addError(ERRORMSG);
            }
            
            
        }
        
        
    }
    
}