force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectProduct__c/ProjectProduct__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>ProjProd{000000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectProduct__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectTeamMembers__c/ProjectTeamMembers__c.object-meta.xml
<CustomObject>
    <label>Project Team Members</label>
    <nameField>
        <displayFormat>ProjTeam{000000}</displayFormat>
        <label>Project Team Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectTeamMembers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Project_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OppTeamMemberTriggerHelper_Test.cls
/**
     *  SFA_TestFactory_Util 
     
     * @author          CTS\Vaishali Thite
     * @version         1.0
     * @date            2017-05-05
     * @description     Opportunity TeamHelper test class
    */
@isTest
private class OppTeamMemberTriggerHelper_Test{
    static testMethod void unitTestOppTeam(){
        test.startTest();
        List<Account> lstAcc =  SFA_TestFactory_Util.createTestAccounts(2);
        System.assertNotEquals(lstAcc.size(),0); 
        List<Opportunity> lstOpp =  SFA_TestFactory_Util.createTestOpportunity(2,lstAcc ); 
        System.assertNotEquals(lstOpp.size(),0); 
        //List<OpportunityLineItem> lstoppItem= SFA_TestFactory_Util.createTestOpportunityLineItem(2,lstOpp);
        //System.assertNotEquals(lstoppItem.size(),0); 
        List<OpportunityTeamMember> lstOppTeam=SFA_TestFactory_Util.createTestOpportunityTeamMember(2,lstOpp); 
        System.assertNotEquals(lstOppTeam.size(),0); 
       /* Project__c prj= SFA_TestFactory_Util.createTestProject(2,lstAcc,lstOpp);
        System.assertNotEquals(prj,Null);
        ProjectProduct__c prjProd=SFA_TestFactory_Util.createTestProjectProduct(prj); 
        List<ProjectTeamMembers__c> lstPrjTeam=SFA_TestFactory_Util.createTestProjectTeamMembers(2,prj,lstOpp);
        System.assertNotEquals(lstPrjTeam.size(),0); */
        
        //Proxy Code Coverage
        OppTeamMemberTriggerHelper oppTeHelper=new OppTeamMemberTriggerHelper(lstOppTeam,lstOppTeam);
        oppTeHelper.addProjectTeam();
        oppTeHelper.deleteMemandSharing();
         //Proxy Code Coverage
        test.stopTest();
    }
}