force-app/main/default/objects/Competitor_Product__c/Competitor_Product__c.object-meta.xml
<CustomObject>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Competitor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Products</relationshipLabel>
    <relationshipName>Competitor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product__c/fields/Positioning__c.field-meta.xml
<CustomField>
    <fullName>Positioning__c</fullName>
    <label>Positioning</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>GMO-free</fullName>
            </value>
            <value>
                <fullName>Natural</fullName>
            </value>
            <value>
                <fullName>Low Calorie</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Healthy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Product__c/fields/Sub_sector_segment_application__c.field-meta.xml
<CustomField>
    <fullName>Sub_sector_segment_application__c</fullName>
    <description>What particular sub sector/segment/application are they focusing on?</description>
    <inlineHelpText>What particular sub sector/segment/application are they focusing on?</inlineHelpText>
    <label>Sub sector/segment/application</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Snacks &amp; cereals</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Confection</fullName>
            </value>
            <value>
                <fullName>Convenience Foods</fullName>
            </value>
            <value>
                <fullName>Infant and Baby Food</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Fruit</fullName>
            </value>
            <value>
                <fullName>Meat</fullName>
            </value>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Pet Food</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountBarGraphs_Test.cls
/*
*    @description:    Test class for SubSectorBarGraphCX & PositioningBarGraphCX.
*    @author:         Sharee Mae Ingatan (sharee.mae.r.ingatan@accenture.com)
*    @createddate:    April 20, 2016
*/
@isTest
public class AccountBarGraphs_Test {
    public static testMethod void SubSectorBarGraphCXTest() {
        RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
        Account newCompetitor = new Account(Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                            );
        newCompetitor.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'].Id;
        insert newCompetitor;
        
        for(Integer i=0; i<2; i++) {
            Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                    Sub_sector_segment_application__c = 'Bakery'
                                                                                    );
            insert newCompetitorProduct;
        }
        
        ApexPages.currentPage().getParameters().put( 'id', newCompetitor.Id );
        
        Test.startTest();
            SubSectorBarGraphCX controller = new SubSectorBarGraphCX(new ApexPages.StandardController(newCompetitor));
            
            controller.positioningCount();
            
            SubSectorBarGraphCX.VerticalBarData wrapper = new SubSectorBarGraphCX.VerticalBarData('Bakery', 1);
            controller.getBarData();
        Test.stopTest();
    }
    
    public static testMethod void PositioningBarGraphCXTest() {
        RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
        Account newCompetitor = new Account(Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                            );
        newCompetitor.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'].Id;                                    
        insert newCompetitor;
        
        for(Integer i=0; i<2; i++) {
            Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                    Positioning__c = 'Natural'
                                                                                    );
            insert newCompetitorProduct;
        }
        
        ApexPages.currentPage().getParameters().put( 'id', newCompetitor.Id );
        
        Test.startTest();
            PositioningBarGraphCX controller = new PositioningBarGraphCX(new ApexPages.StandardController(newCompetitor));
            
            controller.positioningCount();
            
            SubSectorBarGraphCX.VerticalBarData wrapper = new SubSectorBarGraphCX.VerticalBarData('Natural', 1);
            controller.getBarData();
        Test.stopTest();
    }
    public static testMethod void AllPositioningAndSubSectorBarGraphsCCTest() {
        RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
        Account newCompetitor = new Account(Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                            );
        newCompetitor.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'].Id;    
        insert newCompetitor;
        
        for(Integer i=0; i<2; i++) {
            Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                    Sub_sector_segment_application__c = 'Bakery',
                                                                                    Positioning__c = 'Natural'
                                                                                    );
            insert newCompetitorProduct;
        }
        
        ApexPages.currentPage().getParameters().put( 'id', newCompetitor.Id );
        
        Test.startTest();
            AllPositioningAndSubSectorBarGraphsCC controller = new AllPositioningAndSubSectorBarGraphsCC();
            
            controller.subSectorCount();
            controller.positioningCount();
            
            AllPositioningAndSubSectorBarGraphsCC.SubSectorBarData swrapper = new AllPositioningAndSubSectorBarGraphsCC.SubSectorBarData('Bakery', 1);
            controller.getSubSectorBarData();
            
            AllPositioningAndSubSectorBarGraphsCC.PositioningBarData pwrapper = new AllPositioningAndSubSectorBarGraphsCC.PositioningBarData('Bakery', 1);
            controller.getPositioningBarData();
        Test.stopTest();
    }
}