force-app/main/default/objects/Opportunity_RecordType_System_Mapping__mdt/Opportunity_RecordType_System_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Opportunity RecordType System Mapping</label>
    <pluralLabel>Opportunity RecordType System Mapings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity_RecordType_System_Mapping__mdt/fields/Legacy_Systems__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Systems__c</fullName>
    <label>Legacy Systems</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Ship_To__c/Quote_Ship_To__c.object-meta.xml
<CustomObject>
    <label>Quote Ship To</label>
    <nameField>
        <displayFormat>QS-{00000}</displayFormat>
        <label>Quote Ship To Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Ship_To__c/fields/PROS_Quote__c.field-meta.xml
<CustomField>
    <fullName>PROS_Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>CameleonCPQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Ship To&#39;s</relationshipLabel>
    <relationshipName>Quote_Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quote Ship To&#39;s</relationshipLabel>
    <relationshipName>Quote_Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Sold_To__r.Default_Currency__c)</formula>
    <label>Default Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <label>ERP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Global_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System__c</fullName>
    <label>Legacy System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XLGO</fullName>
            </value>
            <value>
                <fullName>XLDM</fullName>
            </value>
            <value>
                <fullName>CBS</fullName>
            </value>
            <value>
                <fullName>CTCM</fullName>
            </value>
            <value>
                <fullName>PROTEAN</fullName>
            </value>
            <value>
                <fullName>FIVE STAR</fullName>
            </value>
            <value>
                <fullName>CFD</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>CVAP EGG</fullName>
            </value>
            <value>
                <fullName>JDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddShipTosToPROSQuoteExtension.cls
public with sharing class AddShipTosToPROSQuoteExtension {
    private CameleonCPQ__Quote__c quote;
    public list<wrapShipTo> lstShipTos{get;set;}
    private string quoteCurrency;
    set<string> setQuoteShipTos = new set<string>();

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public AddShipTosToPROSQuoteExtension(ApexPages.StandardController stdController) {
        this.quote = (CameleonCPQ__Quote__c)stdController.getRecord();       
        CameleonCPQ__Quote__c prosQuote = [SELECT Id,Name,CameleonCPQ__AccountId__c,   OpportunityId__r.recordtype.developerName FROM CameleonCPQ__Quote__c WHERE Id=: this.quote.Id];
        Id accountId = prosQuote.CameleonCPQ__AccountId__c;
        string oppType = prosQuote.OpportunityId__r.recordtype.developerName;
        string oppSystems;
        if(oppType!=null){
            list<Opportunity_RecordType_System_Mapping__mdt> lstOppSystems = [select Legacy_Systems__c from Opportunity_RecordType_System_Mapping__mdt where DeveloperName=:oppType];    
            if(lstOppSystems!=null && lstOppSystems.size()>0){
                oppSystems = lstOppSystems[0].Legacy_Systems__c;
            }
        }
        for(Quote_Ship_To__c qst:[select ship_to__c, ship_to__r.Currency__c from Quote_Ship_To__c where pros_quote__c=:this.quote.id]){
            if(quoteCurrency!=null && qst.ship_to__r.Currency__c!=null){
                quoteCurrency = qst.ship_to__r.Currency__c;
            } 
            setQuoteShipTos.add(qst.ship_to__c);   
        }
        
        if (accountId != null)
        {
            //for(Ship_To__c st : [select Id, Name,Payer__c,description__c,currency__c,City__c,state__c, ERP_Number__c, Legacy_System__c,Commercial_Account__c from Ship_To__c where (Commercial_Account__c = :accountId OR Payer__r.Parentid=:accountId)  AND id not in :setQuoteShipTos AND Status__c = 'Active']) {
            //Pull list of all available Ship Tos
            Boolean alreadySelected = false;
            for(Ship_To__c st : [select Id, Name,Payer__c,description__c,currency__c,City__c,state__c, ERP_Number__c, Legacy_System__c,Commercial_Account__c,Global_Account__c from Ship_To__c where (Commercial_Account__c = :accountId OR Payer__r.Parentid=:accountId OR Global_Account__c=: accountId)  AND Status__c = 'Active']) {
                if(lstShipTos==null){
                    lstShipTos= new list<wrapShipTo>();
                }
                //Check if current Ship-Tos already selected
               	alreadySelected = false;
                if (setQuoteShipTos.contains(st.Id)){
                    alreadySelected =true;
                }
                if(oppSystems!=null && oppType!='Non_CPQ'){
                    if((st.Legacy_System__c!= null)&& (oppSystems.toLowerCase().indexOf(st.Legacy_System__c.toLowerCase() )>=0)){
                        lstShipTos.add(new wrapShipTo(st,alreadySelected));
                    }
                }
                else{
                    lstShipTos.add(new wrapShipTo(st,alreadySelected));
                }
                //lstShipTos.add(new wrapShipTo(st));
            }
        }
    }
    public pageReference backtoQuote(){
        PageReference pageRef = new PageReference('/'+this.quote.id  + '?core.apexpages.devmode.url=1' ); 
        pageRef.setRedirect(true); 
        return pageRef; 
    }
    public pageReference addShipTos(){
        //Delete all ShipTo first
        SmartCPQUtils.removeAllShipTos(this.quote);
        //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
        list<Quote_Ship_To__c> lstQuoteShipTo = new list<Quote_Ship_To__c>();   
        for(wrapShipTo sh:lstShipTos){
            if(sh.selected && (quoteCurrency==null || sh.shipTo.currency__c==quoteCurrency)){
                string externalId = this.quote.Id+'|'+ sh.shipTo.id;
                lstQuoteShipTo.add(new Quote_Ship_To__c(PROS_Quote__c=this.quote.Id, Ship_To__c = sh.shipTo.id, External_Id__c=externalId));    
                system.debug('selected ship:'+sh.shipTo.Name);
            }
            else if(sh.selected && quoteCurrency!=null && sh.shipTo.currency__c==quoteCurrency){
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: All selected Ship To\'s must have same currency!');
                ApexPages.addMessage(errMsg);  
                return null;       
            }
        }
        savePoint sp= database.setSavePoint();
        try{
            upsert lstQuoteShipTo;
        }catch(DmlException ex){
            ApexPages.addMessages(ex); 
            database.Rollback(sp);
            return null;   
        }
        PageReference pageRef = new PageReference('/'+this.quote.id  + '?core.apexpages.devmode.url=1'); 
        pageRef.setRedirect(true); 
        return pageRef; 
    }
    
    public pageReference addAllShipTos(){
        CameleonCPQ__Quote__c prosQuote = [SELECT Id,Name,CameleonCPQ__AccountId__c,OpportunityId__r.recordtype.developerName FROM CameleonCPQ__Quote__c WHERE Id=: this.quote.Id];

        SmartCPQUtils.addAllShipTos(prosQuote,null);
        return this.backToQuote();
    }
    
    public pageReference removeAllShipTos(){
        SmartCPQUtils.removeAllShipTos(quote);
        return this.backToQuote();
    }    
    
    public void selectAllShipTos(){
        for(wrapShipTo sh:lstShipTos){
            sh.setSelected(true);
        }
    }
    
    public void unSelectAllShipTos(){
        for(wrapShipTo sh:lstShipTos){
            sh.setSelected(false);
        }
    }
    
    public wrapShipTo createNewWrapShipTo(SHIP_To__c shipTo){
        wrapShipTo wst = new  wrapShipTo(shipTo,false);
        return wst;
    }
    public class wrapShipTo{
        public boolean selected {get;set;}
        public void setSelected(Boolean isSelected){
            selected = isSelected;
        }
        public Ship_To__c shipTo {get;set;}
        public wrapShipTo(SHIP_To__c shipTo,Boolean alreadySelected){
            this.selected = alreadySelected;
            this.shipTo = shipTo;
        }
    }
}