force-app/main/default/objects/Product_Brand__c/Product_Brand__c.object-meta.xml
<CustomObject>
    <label>Product Brand</label>
    <nameField>
        <displayFormat>PB-{00000}</displayFormat>
        <label>Product Brand</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Brand__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Brands</relationshipLabel>
    <relationshipName>Product_Brands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Brand__c/fields/Product_Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Brand_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Brand Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Groups</relationshipLabel>
    <relationshipName>Opportunity_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <description>text field for user to enter the volume</description>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CPG_ProductBrandHelper_Test.cls
@isTest
private class CPG_ProductBrandHelper_Test{
static testMethod void syncProductBrandObject(){
//creating test Account/Opportunity
list<Account> acc=CPG_TestFactory_Util.createTestAccounts(1); 
            
list<opportunity> opplist=CPG_TestFactory_Util.createTestOpportunity(1,acc);
system.assertEquals(opplist[0].Volume__c, 100);
//Insert Product Group for the Opportunity
Product_Group__c pg=new Product_Group__c(opportunity__c=opplist[0].Id, Volume__c=1000);
insert pg;
list<Product_Group__c> lstProdGrp = new list<Product_Group__c>();
lstProdGrp.add(pg);
CPG_ProductBrandHelper.syncproductGroup(lstProdGrp);
set<string> setProdBrandId =new set<string>();
for(product_brand__c pb:[select product_brand_Id__c from product_brand__c limit 1]){
setProdBrandId.add(pb.id);
}
CPG_ProductBrandHelper.delProductBrand(setProdBrandId);

delete pg;


//Add Opportunity products for the Opportunity            
list<OpportunityLineItem> oltlist=CPG_TestFactory_Util.createTestOpportunityLineItem(2,opplist);   
delete oltlist;
   
}
}