force-app/main/default/objects/Product_Brand__c/Product_Brand__c.object-meta.xml
<CustomObject>
    <label>Product Brand</label>
    <nameField>
        <displayFormat>PB-{00000}</displayFormat>
        <label>Product Brand</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Brand__c/fields/Branded__c.field-meta.xml
<CustomField>
    <fullName>Branded__c</fullName>
    <label>Branded</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Brand__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Brands</relationshipLabel>
    <relationshipName>Product_Brands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Brand__c/fields/Product_Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Brand_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Brand Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Brand__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Brand__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branded__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7-ELEVEN</fullName>
            </value>
            <value>
                <fullName>Advance Pierre</fullName>
            </value>
            <value>
                <fullName>Ahold</fullName>
            </value>
            <value>
                <fullName>Aldi</fullName>
            </value>
            <value>
                <fullName>Allen Brothers Angus</fullName>
            </value>
            <value>
                <fullName>Angus Pride</fullName>
            </value>
            <value>
                <fullName>Applebee&#39;s</fullName>
            </value>
            <value>
                <fullName>Arby&#39;s</fullName>
            </value>
            <value>
                <fullName>Archer Farms</fullName>
            </value>
            <value>
                <fullName>Bachoco</fullName>
            </value>
            <value>
                <fullName>Bakers &amp; Chef</fullName>
            </value>
            <value>
                <fullName>Beef O&#39; Brady</fullName>
            </value>
            <value>
                <fullName>Best Choice</fullName>
            </value>
            <value>
                <fullName>Blackwell Angus</fullName>
            </value>
            <value>
                <fullName>Bob Evan&#39;s</fullName>
            </value>
            <value>
                <fullName>Boston Market</fullName>
            </value>
            <value>
                <fullName>Breeder</fullName>
            </value>
            <value>
                <fullName>Brinker</fullName>
            </value>
            <value>
                <fullName>Brookshires Grocery</fullName>
            </value>
            <value>
                <fullName>Butcher Block Reserve Ang</fullName>
            </value>
            <value>
                <fullName>C/R INGREDIENTS FOR VA</fullName>
            </value>
            <value>
                <fullName>Campbell&#39;s</fullName>
            </value>
            <value>
                <fullName>Cargill Premium Beef</fullName>
            </value>
            <value>
                <fullName>Cargill Value Added Meats</fullName>
            </value>
            <value>
                <fullName>Case Ready Grind Patties</fullName>
            </value>
            <value>
                <fullName>Castle Wood Reserve</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>Cert Angus Bf Path Proven</fullName>
            </value>
            <value>
                <fullName>Certified Angus Beef</fullName>
            </value>
            <value>
                <fullName>Charter Reserve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Branded__c.field-meta.xml
<CustomField>
    <fullName>Branded__c</fullName>
    <label>Branded</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Unbranded</fullName>
            </value>
            <value>
                <fullName>Private Label</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Groups</relationshipLabel>
    <relationshipName>Opportunity_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <description>Protein&#39;s</description>
    <label>Protein</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Chicken</fullName>
            </value>
            <value>
                <fullName>Pork</fullName>
            </value>
            <value>
                <fullName>Eggs</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>CFD - All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Unit_of_Mesure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Mesure__c</fullName>
    <description>Single Value Pick list of Unit of Measure values</description>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitOfMeasure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <description>text field for user to enter the volume</description>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/UnitOfMeasure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pound</fullName>
        <label>Pound (lb)</label>
    </customValue>
    <customValue>
        <fullName>Metric Ton (mt)</fullName>
        <isActive>false</isActive>
        <label>Metric Ton (mt)</label>
    </customValue>
    <customValue>
        <fullName>Kilogram (kg)</fullName>
        <isActive>false</isActive>
        <label>Kilogram (kg)</label>
    </customValue>
    <customValue>
        <fullName>Metric Ton</fullName>
        <isActive>false</isActive>
        <label>Metric Ton</label>
    </customValue>
    <customValue>
        <fullName>Pounds (lbs)</fullName>
        <isActive>false</isActive>
        <label>Pounds (lbs)</label>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
        <isActive>false</isActive>
        <label>Ton (t)</label>
    </customValue>
    <customValue>
        <fullName>Ounce</fullName>
        <isActive>false</isActive>
        <label>Ounce (oz)</label>
    </customValue>
    <masterLabel>Unit of Measure</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CPG_ProductBrandHelper.cls
public class CPG_ProductBrandHelper{
public static void syncproductGroup(list<Product_Group__c> lstProdGrp){
list<Product_brand__c> lstProdBrand = new list<Product_Brand__c>();
    for(Product_Group__c pg:lstProdGrp){
        lstProdBrand.add(new product_brand__c(Opportunity__c=pg.Opportunity__c, protein__c=pg.protein__c, Brand__c=pg.Brand__c, Branded__c=pg.branded__c, volume__c=pg.volume__c, Unit_of_Measure__c = pg.Unit_of_Mesure__c, Product_brand_id__c=pg.id));
    }
    if(!lstProdBrand.isEmpty()){
        upsert lstProdBrand product_brand_id__c;
    }
}

public static void syncOppProduct(list<OpportunityLineItem> lstOppProd){
list<Product_brand__c> lstProdBrand = new list<Product_Brand__c>();
    for(OpportunityLineItem prod:lstOppProd){
        lstProdBrand.add(new product_brand__c(Opportunity__c=prod.OpportunityId, protein__c=prod.protein__c, Brand__c=prod.Brand__c, Branded__c=prod.branded__c, volume__c=prod.Quantity, Unit_of_Measure__c = prod.UnitofMeasure__c, Product_brand_id__c=prod.id));
    }
    if(!lstProdBrand.isEmpty()){
        upsert lstProdBrand product_brand_id__c;
    }
}

public static void delProductBrand(set<string> setProdBrandId){
    list<Product_Brand__c> lstProdBrand = new list<Product_Brand__c>();
    if(!setProdBrandId.isEmpty()){
        lstProdBrand = [select id from product_brand__c where product_brand_id__c in :setProdBrandId];
        if(!lstProdBrand.isEmpty()){
            delete lstProdBrand;
        }
    }
}

}