force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/Competitor_Product__c.object-meta.xml
<CustomObject>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Product__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Competitor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Products</relationshipLabel>
    <relationshipName>Competitor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Product__c/fields/Sub_sector_segment_application__c.field-meta.xml
<CustomField>
    <fullName>Sub_sector_segment_application__c</fullName>
    <description>What particular sub sector/segment/application are they focusing on?</description>
    <inlineHelpText>What particular sub sector/segment/application are they focusing on?</inlineHelpText>
    <label>Sub sector/segment/application</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Snacks &amp; cereals</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Confection</fullName>
            </value>
            <value>
                <fullName>Convenience Foods</fullName>
            </value>
            <value>
                <fullName>Infant and Baby Food</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Fruit</fullName>
            </value>
            <value>
                <fullName>Meat</fullName>
            </value>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Pet Food</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Competitor_Product__c/Opportunity_Competitor_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Competitor Product</label>
    <nameField>
        <displayFormat>OCP-{0000000}</displayFormat>
        <label>Competitor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Competitor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Competitor_Product__c/fields/Competitor_Product__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor Product</label>
    <referenceTo>Competitor_Product__c</referenceTo>
    <relationshipLabel>Opportunity Competitor Products</relationshipLabel>
    <relationshipName>Opportunity_Competitor_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Competitor_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Competitor Products</relationshipLabel>
    <relationshipName>Opportunity_Competitor_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Substitute_Product__c/Substitute_Product__c.object-meta.xml
<CustomObject>
    <description>Junction between Product and Competitor Product</description>
    <label>Related Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Substitute Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Substitute Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Substitute_Product__c/fields/Competitor_Product__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor Product</label>
    <referenceTo>Competitor_Product__c</referenceTo>
    <relationshipLabel>Related Cargill Products</relationshipLabel>
    <relationshipName>Related_Cargill_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Substitute_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Competitive Match</relationshipLabel>
    <relationshipName>Substitute_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddOpportunityCompetitorProductsCX_Test.cls
/*
*    @description:    Test class for AddOpportunityCompetitorProductsCX.
*    @author:         Sharee Mae Ingatan (sharee.mae.r.ingatan@accenture.com)
*    @createddate:    April 20, 2016
*/
@isTest
private class AddOpportunityCompetitorProductsCX_Test {
    //for testing remove button of selected products
    private AddOpportunityCompetitorProductsCX_Test(){}
    public static testMethod void AddOpportunityCompetitorProductsCX_Test1() {
         Account newCompetitor = new Account();
        newCompetitor.Name = 'TestName';
        newCompetitor.BillingCity = 'TestBillingCity';
        newCompetitor.BillingState = 'Iowas';
        newCompetitor.BillingStreet = 'TestBillingStreet';
        newCompetitor.BillingPostalCode = 'TestBilling';
        newCompetitor.ShippingCity = 'TestShippingCity';
        newCompetitor.ShippingState = 'Iowa';
        newCompetitor.ShippingStreet = 'TestShippingStreet';
        newCompetitor.ShippingPostalCode = 'TestShipping';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        //RecordType opportunityRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'New Opportunity'];
        Opportunity newOpportunity = new Opportunity(Name = 'Opportunity Test 1',
                                                        AccountId = newCompetitor.Id,
                                                        CloseDate = System.Today() + 7,
                                                        StageName = 'Rascunho'
                                                        //Numero_de_concorrentes__c = '1'
                                                        );
        insert newOpportunity;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Opportunity_Competitor_Product__c newOpportunityCompetitorProduct = new Opportunity_Competitor_Product__c(Opportunity__c = newOpportunity.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newOpportunity.Id );
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunity);
        Test.startTest();
            AddOpportunityCompetitorProductsCX controller = new AddOpportunityCompetitorProductsCX(new ApexPages.StandardSetController(oppList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            
            AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper wrapper1 = new AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper(newCompetitorProduct, false);
            controller.selectedCompetitorProductId = newCompetitorProduct.Id;
            controller.loadSelectedCompetitorProductsTable();
            List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper> wrapper1List = new List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper>();
            controller.prodId = newCompetitorProduct.Id;
            controller.removeProduct();
        Test.stopTest();
    }
    
    //test without competitor products account/competitor__c
    public static testMethod void AddOpportunityCompetitorProductsCX_Test2() {
        Account newCompetitor = new Account();
        newCompetitor .Name = 'Test1';
        newCompetitor .BillingCity = 'Testc';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Testb';
        newCompetitor .ShippingCity = 'Testsh';
        newCompetitor .ShippingState = 'Iowaa';
        newCompetitor .ShippingStreet = 'Teststr';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        //RecordType opportunityRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'New Opportunity'];
        Opportunity newOpportunity = new Opportunity(Name = 'Opportunity Test 1',
                                                        AccountId = newCompetitor.Id,
                                                        CloseDate = System.Today() + 7,
                                                        StageName = 'Rascunho'
                                                        //Numero_de_concorrentes__c = '1'
                                                        );
        insert newOpportunity;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Opportunity_Competitor_Product__c newOpportunityCompetitorProduct = new Opportunity_Competitor_Product__c(Opportunity__c = newOpportunity.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newOpportunity.Id );
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunity);
        Test.startTest();
            AddOpportunityCompetitorProductsCX controller = new AddOpportunityCompetitorProductsCX(new ApexPages.StandardSetController(oppList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
        Test.stopTest();
    }
    
    //test save
    public static testMethod void AddOpportunityCompetitorProductsCX_Test3() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        //RecordType opportunityRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'New Opportunity'];
        Opportunity newOpportunity = new Opportunity(Name = 'Opportunity Test 1',
                                                        AccountId = newCompetitor.Id,
                                                        CloseDate = System.Today() + 7,
                                                        StageName = 'Rascunho'
                                                        //Numero_de_concorrentes__c = '1'
                                                        );
        insert newOpportunity;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Name = 'Competitor Product Test 1',
                                                                                Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Opportunity_Competitor_Product__c newOpportunityCompetitorProduct = new Opportunity_Competitor_Product__c(Opportunity__c = newOpportunity.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newOpportunity.Id );
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunity);
        Test.startTest();
            AddOpportunityCompetitorProductsCX controller = new AddOpportunityCompetitorProductsCX(new ApexPages.StandardSetController(oppList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            
            AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper wrapper1 = new AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper(newCompetitorProduct, false);
            controller.selectedCompetitorProductId = newCompetitorProduct.Id;
            controller.loadSelectedCompetitorProductsTable();
            List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper> wrapper1List = new List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper>();
            controller.save();
            controller.cancel();
            controller.searchButton();
            controller.searchText = 'Test';
            controller.searchProducts();
        Test.stopTest();
    }
    
    //test search error on save
    public static testMethod void AddOpportunityCompetitorProductsCX_Test4() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        //RecordType opportunityRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'New Opportunity'];
        Opportunity newOpportunity = new Opportunity(Name = 'Opportunity Test 1',
                                                        AccountId = newCompetitor.Id,
                                                        CloseDate = System.Today() + 7,
                                                        StageName = 'Rascunho'
                                                        //Numero_de_concorrentes__c = '1'
                                                        );
        insert newOpportunity;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Opportunity_Competitor_Product__c newOpportunityCompetitorProduct = new Opportunity_Competitor_Product__c(Opportunity__c = newOpportunity.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newOpportunity.Id );
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunity);
        Test.startTest();
            AddOpportunityCompetitorProductsCX controller = new AddOpportunityCompetitorProductsCX(new ApexPages.StandardSetController(oppList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            
            AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper wrapper1 = new AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper(newCompetitorProduct, false);
            controller.selectedCompetitorProductId = newCompetitorProduct.Id;
            controller.loadSelectedCompetitorProductsTable();
            List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper> wrapper1List = new List<AddOpportunityCompetitorProductsCX.CompetitorProductsWrapper>();
            controller.save();
            controller.cancel();
            controller.searchButton();
            controller.searchText = 'Te';
            controller.searchProducts();
        Test.stopTest();
    }
    
    //test search
    public static testMethod void AddOpportunityCompetitorProductsCX_Test5() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        //RecordType opportunityRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'New Opportunity'];
        Opportunity newOpportunity = new Opportunity(Name = 'Opportunity Test 1',
                                                        AccountId = newCompetitor.Id,
                                                        CloseDate = System.Today() + 7,
                                                        StageName = 'Rascunho'
                                                        //Numero_de_concorrentes__c = '1'
                                                        );
        insert newOpportunity;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Opportunity_Competitor_Product__c newOpportunityCompetitorProduct = new Opportunity_Competitor_Product__c(Opportunity__c = newOpportunity.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newOpportunity.Id );
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunity);
        Test.startTest();
            AddOpportunityCompetitorProductsCX controller = new AddOpportunityCompetitorProductsCX(new ApexPages.StandardSetController(oppList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            controller.searchedProdId = newCompetitorProduct.Id;
            controller.addSearchedProduct();
            controller.hideSearchSection();
        Test.stopTest();
    }
    
    
    //for testing remove button of selected products
    public static testMethod void AddCompetitorProductsCX_Test1() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        Product2 newProduct = new Product2(Name = 'Product Test 1',Product_Deployment__c = 'Placeholder',
                                           Enterprise__c = 'FoodIngredientsBioIndustrialFIBI',
                                           Group__c = 'GoToMarket (GTM)', Business__c = 'Commercial Excellence NA'
                                            );
        insert newProduct;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Substitute_Product__c newOpportunityCompetitorProduct = new Substitute_Product__c(Product__c = newProduct.id
                                                                                                                    );
        insert newOpportunityCompetitorProduct;
        
        ApexPages.currentPage().getParameters().put( 'id', newProduct.Id );
        List<Product2> prodList = new List<Product2>();
        prodList.add(newProduct);
        Test.startTest();
            AddCompetitorProductsCX controller = new AddCompetitorProductsCX(new ApexPages.StandardSetController(prodList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            
            AddCompetitorProductsCX.CompetitorProductsWrapper wrapper1 = new AddCompetitorProductsCX.CompetitorProductsWrapper(newCompetitorProduct, false);
            controller.selectedCompetitorProductId = newCompetitorProduct.Id;
            controller.loadSelectedCompetitorProductsTable();
            List<AddCompetitorProductsCX.CompetitorProductsWrapper> wrapper1List = new List<AddCompetitorProductsCX.CompetitorProductsWrapper>();
            controller.prodId = newCompetitorProduct.Id;
            controller.removeProduct();
        Test.stopTest();
    }
    
    public static testMethod void AddCompetitorProductsCX_Test2() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        Product2 newProduct = new Product2(Name = 'Product Test 1',Product_Deployment__c = 'Placeholder',
                                           Enterprise__c = 'FoodIngredientsBioIndustrialFIBI',
                                           Group__c = 'GoToMarket (GTM)', Business__c = 'Commercial Excellence NA'
                                            );
        insert newProduct;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;

        Substitute_Product__c newOpportunityCompetitorProduct = new Substitute_Product__c(Product__c = newProduct.id
                                                                                            );
        insert newOpportunityCompetitorProduct;

        Substitute_Product__c newOpportunityCompetitorProduct2 = new Substitute_Product__c(Product__c = newProduct.id,
                                                                                            Competitor_Product__c = newCompetitorProduct.id
                                                                                            );
        insert newOpportunityCompetitorProduct2;
        
        ApexPages.currentPage().getParameters().put( 'id', newProduct.Id );
        List<Product2> prodList = new List<Product2>();
        prodList.add(newProduct);
        Test.startTest();
            AddCompetitorProductsCX controller = new AddCompetitorProductsCX(new ApexPages.StandardSetController(prodList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            
            AddCompetitorProductsCX.CompetitorProductsWrapper wrapper1 = new AddCompetitorProductsCX.CompetitorProductsWrapper(newCompetitorProduct, false);
            controller.selectedCompetitorProductId = newCompetitorProduct.Id;
            controller.loadSelectedCompetitorProductsTable();
            List<AddCompetitorProductsCX.CompetitorProductsWrapper> wrapper1List = new List<AddCompetitorProductsCX.CompetitorProductsWrapper>();
            AddCompetitorProductsCX.SearchedCompetitorProductsWrapper wrapper2 = new AddCompetitorProductsCX.SearchedCompetitorProductsWrapper(newCompetitorProduct, false);
            List<AddCompetitorProductsCX.SearchedCompetitorProductsWrapper> wrapper2List = new List<AddCompetitorProductsCX.SearchedCompetitorProductsWrapper>();
            controller.save();
            controller.cancel();
            controller.searchButton();
            controller.searchText = 'Test';
            controller.searchProducts();
        Test.stopTest();
    }
    
    public static testMethod void AddCompetitorProductsCX_Test3() {
         Account newCompetitor = new Account();
        newCompetitor .Name = 'Test';
        newCompetitor .BillingCity = 'Test';
        newCompetitor .BillingState = 'Iowa';
        newCompetitor .BillingStreet = 'Test';
        newCompetitor .BillingPostalCode = 'Test';
        newCompetitor .ShippingCity = 'Test';
        newCompetitor .ShippingState = 'Iowa';
        newCompetitor .ShippingStreet = 'Test';
        newCompetitor .ShippingPostalCode = 'Test';
        newCompetitor.Market_Channel__c='Retail Channel';
        insert newCompetitor;
        
        Product2 newProduct = new Product2(Name = 'Product Test 1',Product_Deployment__c = 'Placeholder',
                                           Enterprise__c = 'FoodIngredientsBioIndustrialFIBI',
                                           Group__c = 'GoToMarket (GTM)', Business__c = 'Commercial Excellence NA'
                                            );
        insert newProduct;
        
        Competitor_Product__c newCompetitorProduct = new Competitor_Product__c(Competitor__c = newCompetitor.Id,
                                                                                Sub_sector_segment_application__c = 'Bakery'
                                                                                );
        insert newCompetitorProduct;
        
        Substitute_Product__c newOpportunityCompetitorProduct = new Substitute_Product__c(Product__c = newProduct.id
                                                                                            );
        insert newOpportunityCompetitorProduct;

        Substitute_Product__c newOpportunityCompetitorProduct2 = new Substitute_Product__c(Product__c = newProduct.id,
                                                                                            Competitor_Product__c = newCompetitorProduct.id
                                                                                            );
        insert newOpportunityCompetitorProduct2;
        
        ApexPages.currentPage().getParameters().put( 'id', newProduct.Id );
        List<Product2> prodList = new List<Product2>();
        prodList.add(newProduct);
        Test.startTest();
            AddCompetitorProductsCX controller = new AddCompetitorProductsCX(new ApexPages.StandardSetController(prodList));
            
            controller.getCompetitors();
            controller.getCompetitorProducts();
            controller.searchedProdId = newCompetitorProduct.Id;
            controller.addSearchedProduct();
            controller.hideSearchSection();
        Test.stopTest();
    }
}