force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/BusinessDetail__c.object-meta.xml
<CustomObject>
    <label>Business Detail</label>
    <nameField>
        <label>Business Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/PrimaryBusinessContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryBusinessContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Business Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BusinessUnitDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BusinessUnitDetailCompController_Test.cls
@isTest
private class BusinessUnitDetailCompController_Test{
    static testMethod void validateHelper(){
        Account acc1= new Account();
        acc1.Name ='TestAccount';
        acc1.BillingCity ='Chennai' ;
        acc1.BillingCountry='india';         
        acc1.BillingPostalCode='600075';
        acc1.BillingState='tamil nadu';
        acc1.BillingStreet='water well street';  
        acc1.ShippingCity='Chennai';
        acc1.ShippingCountry='india';         
        acc1.ShippingPostalCode='600075';
        acc1.ShippingState='tamil nadu';
        acc1.ShippingStreet='waterr well street';
        acc1.Market_Channel__c='Retail Channel';
        insert acc1;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'SysAdm', Email='systemadmin@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles',Cargill_Business_Unit__c='Commercial Excellence NA',CargillRegion__c = 'South America (SA)',CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI',CargillGroup__c='GoToMarket (GTM)', UserName='standarduser22@testorg.com');
        insert u;
        
        AccountTeamMember aa = new AccountTeamMember();
        aa.UserId= u.Id;
        aa.AccountId =acc1.Id;
        insert aa; 
        
        
        Business__c bb= new Business__c();
        bb.Name = 'test';
        bb.BusinessUnitAlias__c ='GTM Corp Accts';
        bb.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        bb.CargillGroup__c = 'GoToMarket (GTM)';
        
        insert bb;
        
        
        BusinessDetail__c bd = new BusinessDetail__c();
        bd.Name = 'test';
        bd.Account__c = acc1.Id;
        bd.BusinessUnit__c =bb.Id;
        bd.Status__c = 'Active';
        bd.PrimaryBusinessContact__c = u.Id;
        insert bd;
        
        List<BusinessDetail__c> listbud =[select Id from BusinessDetail__c];
        //String idb = [select Id from BusinessDetail__c LIMIT 1].Id;
        BusinessUnitDetailCompController callm = new BusinessUnitDetailCompController();
        BusinessUnitDetailCompController.getBusinessUnitDetail(acc1.Id);
        BusinessUnitDetailCompController.getCurrentUserBusinessUnit();
        BusinessUnitDetailCompController.getAccountTeamList('Go To Market Corporate Accounts',acc1.Id);
        BusinessUnitDetailCompController.getCurrentUserBusinessUnit(listbud);
        BusinessUnitDetailCompController.updateBusinessUnitDetail(listbud);
        BusinessUnitDetailCompController.getUpdatedBusinessDetail(bd.Id);
        
    }
}