force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Meeting_Attendee__c/Customer_Meeting_Attendee__c.object-meta.xml
<CustomObject>
    <label>Cargill Attendee Details</label>
    <nameField>
        <displayFormat>Att-{00000}</displayFormat>
        <label>Customer Meeting Attendees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargill Attendee Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Meeting_Attendee__c/fields/Cargill_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Cargill_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargill Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Meeting_Attendee__c/fields/Customer_Meeting_Report__c.field-meta.xml
<CustomField>
    <fullName>Customer_Meeting_Report__c</fullName>
    <label>Customer Meeting Report</label>
    <referenceTo>CustomerMeetingReport__c</referenceTo>
    <relationshipName>Cargill_Meeting_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Meeting_Contact__c/Customer_Meeting_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Representative</label>
    <nameField>
        <displayFormat>Con-{00000}</displayFormat>
        <label>Customer Meeting Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Meeting Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Meeting_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Meeting Representatives</relationshipLabel>
    <relationshipName>Customer_Meeting_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Meeting_Contact__c/fields/Customer_Meeting_Report__c.field-meta.xml
<CustomField>
    <fullName>Customer_Meeting_Report__c</fullName>
    <label>Customer Meeting Report</label>
    <referenceTo>CustomerMeetingReport__c</referenceTo>
    <relationshipName>Customer_Meeting_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/CustomerMeetingReport__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report</label>
    <nameField>
        <label>Customer Meeting Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Meeting Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cargill Business Detail relationship.</description>
    <inlineHelpText>Cargill Business Detail relationship.</inlineHelpText>
    <label>Business</label>
    <referenceTo>BusinessDetail__c</referenceTo>
    <relationshipLabel>Customer Meeting Reports</relationshipLabel>
    <relationshipName>Customer_Meeting_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaskTriggerHelper_Test.cls
@isTest
public class TaskTriggerHelper_Test {
    static testMethod void validateHelper(){
        Business__c b = new Business__c();
        b.BusinessUnitAlias__c = 'Foods Brazil';
        b.Name = 'Cargill Foods Brazil';
        b.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        b.CargillGroup__c = 'GoToMarket (GTM)';
        Insert b;
        
        
        Task insertNew = new Task();
        insertNew.Subject ='Test';
        insertNew.OwnerId = CPG_TestFactory_Util.createTestUser('System Administrator').id;
        insertNew.Priority = 'Normal';
        insertNew.Status ='Open';
        Insert insertNew;
    }
    static testMethod void validateCMRtaskRollup(){
        //create account       
        list<Account> acclist=CPG_TestFactory_Util.createTestAccounts(2);
        acclist[0].Parentid=acclist[1].id;
        update acclist[0];
        
        //Create Contact
        list<contact> lstCon = new list<contact>();
        lstCon = CPG_TestFactory_Util.createTestContacts(2,acclist);
        
        //Create Cargill Attendee
        user attendee = CPG_TestFactory_Util.createTestUser('System Administrator');
        user attendee2 = CPG_TestFactory_Util.createTestUser('System Administrator');
           
        //Create Customer Meeting report   
        list<CustomerMeetingReport__c> lstCMR = CPG_TestFactory_Util.createTestCustomerMeetingReport(1,acclist);
        
        //Add Attendees to CMR
        list<Customer_Meeting_Attendee__c> lstAtt = new list<Customer_Meeting_Attendee__c>();
        lstAtt.add(new Customer_Meeting_Attendee__c(Cargill_Attendee__c=attendee.id, customer_meeting_report__c = lstCMR[0].id));
        lstAtt.add(new Customer_Meeting_Attendee__c(Cargill_Attendee__c=attendee2.id, customer_meeting_report__c = lstCMR[0].id));
        insert lstAtt;
        
        //Add Customer Attendees to CMR
        list<Customer_Meeting_Contact__c> lstConAtt = new list<Customer_Meeting_Contact__c>();
        lstConAtt.add(new Customer_Meeting_Contact__c(contact__c=lstCon[0].id, customer_meeting_report__c = lstCMR[0].id));
        lstConAtt.add(new Customer_Meeting_Contact__c(contact__c=lstCon [1].id, customer_meeting_report__c = lstCMR[0].id));
        insert lstConAtt;
        
        //Create Tasks against CMR
        list<task> lstTask = new list<task>();
        Task insertNew1 = new Task();
        insertNew1.Subject ='Test';
        insertNew1.OwnerId = attendee.id;
        insertNew1.Priority = 'Normal';
        insertNew1.Status ='Open';
        insertNew1.whatid = lstCMR[0].id;
        lstTask.add(insertNew1);
        
        Task insertNew2 = new Task();
        insertNew2.Subject ='Test';
        insertNew2.OwnerId = attendee.id;
        insertNew2.Priority = 'Normal';
        insertNew2.Status ='Open';
        insertNew2.whatid = lstCMR[0].id;
        lstTask.add(insertNew2);
        Insert lstTask;
        delete lstTask[0];
        
    }
}