force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/BusinessDetail__c.object-meta.xml
<CustomObject>
    <label>Business Detail</label>
    <nameField>
        <label>Business Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloneOpportunityController_Test.cls
/**
 Test class to cover functionality of class: cloneOpportunityController
 */
@isTest
private class CloneOpportunityController_Test {
	private CloneOpportunityController_Test(){}
    static testMethod void myUnitTest() {
        
		Map<String,Schema.RecordTypeInfo> recordTypeMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingCity = 'Test';
        acc.BillingState = 'Iowa';
        acc.BillingStreet = 'Test';
        acc.BillingPostalCode = 'Test';
        acc.ShippingCity = 'Test';
        acc.ShippingState = 'Iowa';
        acc.ShippingStreet = 'Test';
        acc.ShippingPostalCode = 'Test';
        acc.RecordTypeId= recordTypeMap.get('Global Account').getRecordTypeId();
        acc.Market_Channel__c='Retail Channel';
        insert(acc);
        
        Opportunity opp = new Opportunity();
        opp.Name='Test'; 
        opp.NextStep='test';                                   
        opp.CloseDate = System.today();                                    
        opp.AccountId=acc.id; 
        opp.StageName='Closed Won - One Time'; 
        opp.Probability=100;
        insert(opp);
        
        Business__c bUnit = new Business__c();
        bUnit.Name = 'Teat';
        bUnit.BusinessUnitAlias__c = 'GTM Corp Accts';
        bUnit.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        bUnit.CargillGroup__c = 'GoToMarket (GTM)';
        insert(bUnit);
        
        BusinessDetail__c bDetails = new BusinessDetail__c();
        bDetails.Account__c = acc.Id;
        bDetails.BusinessUnit__c = bUnit.Id;
        bDetails.Status__c = 'Active';
        insert(bDetails);
        
				
		Product2 prd1 = new Product2 (Name='Test Product Entry 1',Description='Test Product Entry 1',productCode = 'ABC', isActive = true,Business__c='Commercial Excellence NA',Product_Deployment__c='Placeholder');
		insert prd1;
		
		
		PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=Test.getStandardPricebookId(),UnitPrice=50, isActive=true);
		insert pbe1;
		
				
		OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=opp.id,PriceBookEntryID=pbe1.id, quantity=4, totalprice=200);
		insert lineItem1;
		
		Test.StartTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(opp);
			cloneOpportunityController cloneOpp = new cloneOpportunityController(sc);
			cloneOpp.opportunityId = opp.id;
			cloneOpp.Save();
			
			
		Test.StopTest();
        
    }
}