force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditLimit__c/CreditLimit__c.object-meta.xml
<CustomObject>
    <label>Credit Limit</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Credit Limit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Limits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReport__c/CustomerMeetingReport__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report</label>
    <nameField>
        <label>Customer Meeting Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Meeting Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cargill Business Detail relationship.</description>
    <inlineHelpText>Cargill Business Detail relationship.</inlineHelpText>
    <label>Business</label>
    <referenceTo>BusinessDetail__c</referenceTo>
    <relationshipLabel>Customer Meeting Reports</relationshipLabel>
    <relationshipName>Customer_Meeting_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_10__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_10__c</fullName>
    <label>Related Task 10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_1__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_1__c</fullName>
    <label>Related Task 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_2__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_2__c</fullName>
    <label>Related Task 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_3__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_3__c</fullName>
    <label>Related Task 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_4__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_4__c</fullName>
    <label>Related Task 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_5__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_5__c</fullName>
    <label>Related Task 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_6__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_6__c</fullName>
    <label>Related Task 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_7__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_7__c</fullName>
    <label>Related Task 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_8__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_8__c</fullName>
    <label>Related Task 8</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Related_Task_9__c.field-meta.xml
<CustomField>
    <fullName>Related_Task_9__c</fullName>
    <label>Related Task 9</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExtraInformation__c/ExtraInformation__c.object-meta.xml
<CustomObject>
    <label>Extra Information</label>
    <nameField>
        <displayFormat>Extra Info - {000000}</displayFormat>
        <label>Extra Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extra Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraInformation__c/fields/ShipTo__c.field-meta.xml
<CustomField>
    <fullName>ShipTo__c</fullName>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Extra Informations</relationshipLabel>
    <relationshipName>Extra_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/TelesalesPlan__c/TelesalesPlan__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlan__c/recordTypes/ContingencyPlan.recordType-meta.xml
<RecordType>
    <fullName>ContingencyPlan</fullName>
    <active>true</active>
    <label>Contingency Plan</label>
</RecordType>

force-app/main/default/objects/TelesalesPlan__c/recordTypes/WorkPlan.recordType-meta.xml
<RecordType>
    <fullName>WorkPlan</fullName>
    <active>true</active>
    <label>Work Plan</label>
</RecordType>

force-app/main/default/objects/TelesalesPlanDetail__c/TelesalesPlanDetail__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan Detail</label>
    <nameField>
        <displayFormat>TPD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/TelesalesPlan__c.field-meta.xml
<CustomField>
    <fullName>TelesalesPlan__c</fullName>
    <label>TelesalesPlan</label>
    <referenceTo>TelesalesPlan__c</referenceTo>
    <relationshipName>TelesalesPlanDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHelper.cls
/*********************************************************************
Author: sanhita.hegde(sanhita.hegde@accenture.com)
class:TaskHelper
Description: Helps "MastertTask" trigger
************************************************************************/
public with sharing class TaskTriggerHelper {
    Private List<Task> newTaskList = new List<Task>();
    /*********************************************************************
Author: sanhita.hegde(sanhita.hegde@accenture.com)
class:TaskHelper
Description: constructor
************************************************************************/
    public TaskTriggerHelper( List<Task> newTriggerList){
        newTaskList = newTriggerList ;
        
    }
    public void scheduleTask(){
        List<Task> lstNewTasks = new List<Task>();
        for(Task t : newTaskList) {
            if (t.TypeTask__c=='WorkPlan' || t.TypeTask__c=='ContingencyPlan'){
                if(t.RescheduledDate__c!=null && t.ActivityDate!=null && t.RescheduledTime__c!=null && t.TimeToCall__c!=null){
                    if(t.RescheduledDate__c==t.ActivityDate && t.RescheduledTime__c != t.TimeToCall__c ){//same day
                        t.Status = 'CallBack';
                        t.TimeToCall__c = t.RescheduledTime__c ;
                    } else {//diferent dat
                        t.Status = 'Completed';
                        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
                        String finalUrl = sfdcBaseURL + '/' + t.Id;
                        Task newTask = new Task (
                            WhatId = t.WhatId,
                            WhoId = t.WhoId,
                            OwnerId = t.OwnerId,
                            Status = 'Open',
                            TelesalesPlan__c = t.TelesalesPlan__c,
                            Priority = t.Priority,
                            TypeTask__c = t.TypeTask__c,
                            ActivityDate = t.RescheduledDate__c,
                            ShipTo__c = t.ShipTo__c,
                            CreditLimit__c = t.CreditLimit__c,
                            ExtraInformation__c = t.ExtraInformation__c,
                            CurrencyIsoCode = t.CurrencyIsoCode,
                            Subject = t.Subject,
                            TimeToCall__c = t.RescheduledTime__c,
                            TelesalesPlanDetail__c = t.TelesalesPlanDetail__c,
                            RescheduledTask__c = true,
                            LinkSourceTask__c=finalUrl
                        );
                        lstNewTasks.add(newTask);
                    }
                }
            }
        }
        if(!lstNewTasks.isEmpty()){
            insert lstNewTasks;
        }
    }
    /*****************************************************************************************************************************
Author:sanhita.hegde
Description: Populate the Business__c  field on Task by cargill_Business_Unit__c  from Assigned user record.
method name : populateBisiness()
*********************************************************************************************************************************/
    public void populateBusiness(){
        try{
            List<Id> taskOwnerId = new List<Id>();
            For(Task t:newTaskList){
                taskOwnerId.add(t.OwnerId);
            }
            Map<Id,String> userBusiness = new Map<Id,String>();
            //get the cargill_Business_Unit__c from Assigned User 
            for(User u:[select Id,cargill_Business_Unit__c from User where Id IN:taskOwnerId LIMIT 10000]){
                userBusiness.put(u.Id,u.cargill_Business_Unit__c);
            }
            //get the Id of Business record so that we can assign it to look up field.
            Map<String,Id> businessUnitMap = new Map<String,Id>();
            for(Business__c bUnit:[select Id,Name from Business__c where Name IN:userBusiness.Values() LIMIT 10000]){
                businessUnitMap.put(bUnit.Name,bUnit.Id);
            }
            For(Task t:newTaskList){
                if(t.Business__c == null){
                    t.Business__c = businessUnitMap.get(userBusiness.get(t.OwnerId));
                }
            }
        }
        catch(Exception e){
            Throw e;
        }
    }
    //Method to populate related Open tasks on Customer Meeting record
    public static void updateCustMeetingTasks(set<id> setMeetingTasks){
        map<id,list<string>> mapCMRtasks = new map<id,list<string>>();
        map<id,CustomerMeetingReport__c> mapCMR = new map<id,CustomerMeetingReport__c>();
        for(task iTask:[select id,whatId,who.Name,owner.Name,subject,ActivityDate   from task where whatid in :setMeetingTasks and status='Open'order by ActivityDate ASC]){
            if(mapCMRtasks.isEmpty() || (!mapCMRtasks.isEmpty() && !mapCMRtasks.containsKey(iTask.whatId))){
                list<string> temp = new list<string>();
                string tempTask = iTask.subject+', Assigned To: '+ iTask.owner.Name+' Due Date:'+iTask.ActivityDate;
                temp.add(tempTask );
                mapCMRtasks.put(iTask.whatid, temp);
            }
            else{
               string tempTask = iTask.subject+', Assigned To: '+ iTask.owner.Name+' Due Date:'+iTask.ActivityDate;
               mapCMRtasks.get(iTask.whatid).add(tempTask); 
            }
        }
        
        for(id CMRid:setMeetingTasks){
            CustomerMeetingReport__c iCMR = new CustomerMeetingreport__c();
            iCMR.id = CMRid;
            iCMR.related_task_1__c=null;
            iCMR.related_task_2__c=null;
            iCMR.related_task_3__c=null;
            iCMR.related_task_4__c=null;
            iCMR.related_task_5__c=null;
            iCMR.related_task_6__c=null;
            iCMR.related_task_7__c=null;
            iCMR.related_task_8__c=null;
            iCMR.related_task_9__c=null;
            iCMR.related_task_10__c=null;
            mapCMR.put(CMRid, iCMR);
        }
        if(!mapCMRtasks.isEmpty()){
            for(id CMRId:mapCMR.KeySet()){
                for(integer i=1; i<=10 && i<=mapCMRtasks.get(CMRId).size(); i++){
                    string iField = 'related_task_'+i+'__c';
                    mapCMR.get(CMRid).put(iField,mapCMRtasks.get(CMRId)[i-1]);    
                }
            }
        }
        if(!mapCMR.isEmpty()){
            update mapCMR.values();
        }
    }
}