force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/BusinessDetail__c.object-meta.xml
<CustomObject>
    <label>Business Detail</label>
    <nameField>
        <label>Business Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cargill_Leap_App_Config__c/Cargill_Leap_App_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cargill Leap App Config</label>
</CustomObject>

force-app/main/default/objects/Cargill_Leap_App_Config__c/fields/AccountActivityDefaultDisplayNummber__c.field-meta.xml
<CustomField>
    <fullName>AccountActivityDefaultDisplayNummber__c</fullName>
    <label>AccountActivityDefaultDisplayNummber</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cargill_Leap_App_Config__c/fields/AccountActivityObjectList__c.field-meta.xml
<CustomField>
    <fullName>AccountActivityObjectList__c</fullName>
    <label>AccountActivityObjectList</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cargill_Leap_App_Config__c/fields/Status_Filter_List__c.field-meta.xml
<CustomField>
    <fullName>Status_Filter_List__c</fullName>
    <label>Status Filter List</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountActivityListCompControllerTest.cls
/****************************************
Name-AccountActivityListCompController_Test
Author-Heena
Created Date- 9/1/2017
Req No-
Description-this is test class for retrieving task records of related object records to particular account
******************************************/

@isTest
public without sharing class AccountActivityListCompControllerTest{
   
  
  private Static testMethod void retrieveActivityObjectListTest() {
        Cargill_Leap_App_Config__c leap = new Cargill_Leap_App_Config__c();
        leap.AccountActivityDefaultDisplayNummber__c = 100;
        leap.AccountActivityObjectList__c = 'Contact,Opportunity';
        leap.Status_Filter_List__c = 'Open';
        insert(leap);
        
        Test.startTest();   
        AccountActivityListCompController.retrieveActivityObjectList();
        Test.stopTest();
        system.assert(true);
    }
    private Static testMethod void createActivityObjectListTest() {
        Cargill_Leap_App_Config__c leap = new Cargill_Leap_App_Config__c();
        leap.AccountActivityDefaultDisplayNummber__c = 100;
        leap.AccountActivityObjectList__c = 'Opportunity,BusinessDetail__c';
        leap.Status_Filter_List__c = 'Open';
        insert(leap);
        
        Account acc = new Account();
        acc.Name = 'TestName';
        acc.BillingCity = 'TestBillingCity';
        acc.BillingState = 'Iowa';
        acc.BillingStreet = 'TestBillingStreet';
        acc.BillingPostalCode = 'TestBilling';
        acc.ShippingCity = 'TestShippingCity';
        acc.ShippingState = 'Iowa';
        acc.ShippingStreet = 'TestShippingStreet';
        acc.ShippingPostalCode = 'TestShipping';
        acc.Market_Channel__c='Retail Channel';
        insert(acc);
        
        String recordId = acc.Id;
        
        Opportunity opp = new Opportunity();
        opp.Name='TestOpp'; 
        //opp.RenewalDate__c = system.today();                                        
        opp.NextStep='testNextStep';                                   
        opp.CloseDate = System.today();                                    
        opp.AccountId=acc.id; 
        opp.StageName='Closed Won - One Time'; 
        opp.Probability=100;
        insert(opp);
        
        Task tsk1 = new Task();          
        tsk1.Subject = 'other';
        tsk1.Status = 'open';
        tsk1.ActivityDate = system.today();
        tsk1.WhatId = opp.Id;
        insert(tsk1);
        
        Business__c bUnit = new Business__c();
        bUnit.Name = 'Teat';
        bUnit.BusinessUnitAlias__c = 'GTM Corp Accts';
        bUnit.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        bUnit.CargillGroup__c = 'GoToMarket (GTM)';
        insert(bUnit);
        
        BusinessDetail__c bDetails = new BusinessDetail__c();
        bDetails.Account__c = acc.Id;
        bDetails.BusinessUnit__c = BUnit.Id;
        bDetails.Status__c = 'Active';
        insert(bDetails);
        
        Task tsk = new Task();          
        tsk.Subject = 'other';
        tsk.Status = 'open';
        tsk.ActivityDate = system.today();
        tsk.WhatId = BDetails.Id;
        insert(tsk);
        
        Test.startTest();    
        AccountActivityListCompController.createActivityObjectList(recordId);
        Test.stopTest();
        system.assert(true);
    }
    private Static testMethod void getObjectSpecificTaskListTest() {
        Cargill_Leap_App_Config__c leap = new Cargill_Leap_App_Config__c();
        leap.AccountActivityDefaultDisplayNummber__c = 100;
        leap.AccountActivityObjectList__c = 'Opportunity,BusinessDetail__c';
        leap.Status_Filter_List__c = 'Open';
        insert(leap);
        
       /*Cargill_Leap_App_Config__c leap1 = new Cargill_Leap_App_Config__c();
        leap1.AccountActivityDefaultDisplayNummber__c = 100;
        leap1.AccountActivityObjectList__c = 'BusinessDetail__c';
        leap1.Status_Filter_List__c = 'Completed';
        insert(leap1);*/
        
    
     Account acc = new Account();
        acc.Name = 'TestAcc';
        acc.BillingCity = 'Pune';
        acc.BillingState = 'Iowa';
        acc.BillingStreet = 'Iowa';
        acc.BillingPostalCode = 'TestCode';
        acc.ShippingCity = 'TestCity';
        acc.ShippingState = 'Iowa';
        acc.ShippingStreet = 'TestStreet';
        acc.ShippingPostalCode = 'TestPoCode';
        acc.Market_Channel__c='Retail Channel';
        insert(acc);
                
        String recordID = acc.Id; 
        String selectedObj = 'Opportunity';
        String recordID1 = acc.Id; 
        String selectedObj1 = 'Business Detail';
       
        Opportunity opp = new Opportunity();
        opp.Name='TestOppName'; 
        //  Account = acc1, 
        //opp.RenewalDate__c = system.today();                                        
        opp.NextStep='testNStep';                                   
        opp.CloseDate = System.today();                                    
        opp.AccountId=acc.id; 
        opp.StageName='Closed Won - One Time'; 
        opp.Probability=100;
        insert(opp);
        
        Task tsk1 = new Task();          
        tsk1.Subject = 'other';
        tsk1.Status = 'open';
        tsk1.ActivityDate = system.today();
        tsk1.WhatId = opp.Id;
        insert(tsk1); 
        
        Business__c bUnit = new Business__c();
        BUnit.Name = 'Teat';
        BUnit.BusinessUnitAlias__c = 'GTM Corp Accts';
        BUnit.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        BUnit.CargillGroup__c = 'GoToMarket (GTM)';
        insert(BUnit);
        
        BusinessDetail__c bDetails = new BusinessDetail__c();
        BDetails.Account__c = acc.Id;
        BDetails.BusinessUnit__c = BUnit.Id;
        BDetails.Status__c = 'Active';
        insert(BDetails);
        
        Task tsk = new Task();          
        tsk.Subject = 'other';
        tsk.Status = 'open';
        tsk.ActivityDate = system.today();
        tsk.WhatId = BDetails.Id;
        insert(tsk);
        
        Test.startTest(); 
        AccountActivityListCompController.getObjectSpecificTaskList(recordID,selectedObj);
        AccountActivityListCompController.getObjectSpecificTaskList(recordID1,selectedObj1);
        Test.stopTest();    
    }
}