force-app/main/default/objects/CustomerMeetingReport__c/CustomerMeetingReport__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report</label>
    <nameField>
        <label>Customer Meeting Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Meeting Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReport__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Competitor, Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Meeting Reports</relationshipLabel>
    <relationshipName>Customer_Meeting_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CPG_CustomerMeetinReportTriggerTest.cls
@isTest

public class CPG_CustomerMeetinReportTriggerTest{
 @isTest static void TestCustomerMeetingReport(){
      
     CustomerMeetingReport__c customerMeetingReport = new CustomerMeetingReport__c ();
      List<Account> records = [select Id from Account order by CreatedDate DESC limit 1];
      if(records.size() > 0){
      for(Account acc : records){
            customerMeetingReport.Account__c = acc.id;
      }

      }
      
      
      customerMeetingReport.Name = 'Test CMR Trigger';

        insert customerMeetingReport;     
      

  
 }


}