force-app/main/default/objects/CustomerMeetingReport__c/CustomerMeetingReport__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report</label>
    <nameField>
        <label>Customer Meeting Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Meeting Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReportOpp__c/CustomerMeetingReportOpp__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report Opp</label>
    <nameField>
        <displayFormat>CMROpp{000000}</displayFormat>
        <label>Customer Meeting Report Opp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Meeting Report Opps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReportOpp__c/fields/CustomerMeetingReport__c.field-meta.xml
<CustomField>
    <fullName>CustomerMeetingReport__c</fullName>
    <label>Customer Meeting Report</label>
    <referenceTo>CustomerMeetingReport__c</referenceTo>
    <relationshipLabel>Customer Meeting Opportunities</relationshipLabel>
    <relationshipName>Customer_Meeting_Report_Opps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerMeetingReportOpp__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Meeting Report</relationshipLabel>
    <relationshipName>Customer_Meeting_Report_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Protein_OpportunityTriggerHelper_Test.cls
@isTest
public class Protein_OpportunityTriggerHelper_Test {
    public static testMethod void blockOppDeletionWithCMRs_test() {
        Protein_TestDataFactory.insertCustomIntegrationProfileDetail();
        Account commercialAccount = Protein_TestDataFactory.createAccountRecord('Test Commercial Account', Protein_TestDataFactory.COMMERCIALACCOUNT_RECORD_TYPE, 
	        																	Protein_TestDataFactory.FOODSERVICE_MARKETCHANNEL);
        Opportunity opp = Protein_TestDataFactory.createOpportunityRecord('Test Opp', Protein_TestDataFactory.EGG_OPP_RT, commercialAccount.Id,
                                                                          100, Protein_TestDataFactory.EXPLORE_OPP_STAGE, System.today().addDays(20),
                                                                         Protein_TestDataFactory.POUND_OPP_UOM);
        CustomerMeetingReport__c cmr = Protein_TestDataFactory.createCustomerMeetingReportRecord(commercialAccount.Id);
        CustomerMeetingReportOpp__c cmro = Protein_TestDataFactory.createCustomerMeetingReportOppRecord(cmr.Id, opp.Id);
        //The below lines are the code coverage for the Apex Trigger 'Protein_CustomerMeetingReportOppTrigger'
        Opportunity opp1 = Protein_TestDataFactory.createOpportunityRecord('Test Opp1', Protein_TestDataFactory.EGG_OPP_RT, commercialAccount.Id,
                                                                          100, Protein_TestDataFactory.EXPLORE_OPP_STAGE, System.today().addDays(20),
                                                                         Protein_TestDataFactory.POUND_OPP_UOM);
        cmro.Opportunity__c = opp1.Id;
        update cmro;
        //The code for the above mentioned trigger coverage ends here.
        try{
            delete opp;
        }
        catch(DMLException ex){
            system.debug('Error msg: '+ex.getDmlMessage(0));
            System.assertEquals('You cannot delete this Opportunity as it has one or more Customer Meeting Reports attached to it.', ex.getDmlMessage(0));
        }
        
    }

}