force-app/main/default/objects/ChatterPostGroupMention__c/ChatterPostGroupMention__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The  Chatter groups that will be mentioned on  the new Chatter post for every new Competitor Intelligence Record

To get the ID of the Chatter Group, go to User menu-&gt; Developer Console -&gt; Query Editor tab -&gt; Enter &quot;SELECT id, name  FROM CollaborationGroup&quot; -&gt; Click Execute</description>
    <label>ChatterPostGroupMention</label>
</CustomObject>

force-app/main/default/objects/ChatterPostGroupMention__c/fields/Competitive_Intelligence_Type__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Intelligence_Type__c</fullName>
    <label>Competitive Intelligence Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_Intelligence__c/Competitor_Intelligence__c.object-meta.xml
<CustomObject>
    <label>Competitor Intelligence</label>
    <nameField>
        <label>Competitor Intelligence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Intelligence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Intelligence__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Intelligence</relationshipLabel>
    <relationshipName>Competitor_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Intelligence__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisitions / Joint Ventures</fullName>
            </value>
            <value>
                <fullName>Hot Topic</fullName>
            </value>
            <value>
                <fullName>Intelligence</fullName>
            </value>
            <value>
                <fullName>Org Resources Change</fullName>
            </value>
            <value>
                <fullName>Rumor</fullName>
            </value>
            <value>
                <fullName>Technoology Trend / Capability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompetitorIntelligenceTHandler_Test.cls
/**
 Test class to cover functionality of class: CompetitorIntelligenceTriggerHandler
 */
 //seeAlldata is true to access ConnectApi
@isTest(SeeAllData=true) 
private class CompetitorIntelligenceTHandler_Test {
	public static Account newCompetitor;
	public static CollaborationGroup newChatterGroup;
	public static Competitor_Intelligence__c newCompetitorIntelligence;
	
	//method to create test data
	public static void createTestData()
	{
		Map<String,Schema.RecordTypeInfo> recordTypeMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        newCompetitor = new Account(RecordTypeId = recordTypeMap.get('Competitor').getRecordTypeId(),
                          Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                          );
        insert newCompetitor;
        
        newChatterGroup = new CollaborationGroup(Name = 'Chatter Group Test 1',
                                      CollaborationType = 'Public'
                                      );
        insert newChatterGroup;
        
        ChatterPostGroupMention__c chatterGroupSetting = new ChatterPostGroupMention__c(Name = 'Chatter Group Setting Test 1',
                                                Group_Id__c = newChatterGroup.Id,
                                                Competitive_Intelligence_Type__c = 'Intelligence'
                                                );
        insert chatterGroupSetting;
        
        newCompetitorIntelligence = new Competitor_Intelligence__c(Competitor__c = newCompetitor.Id,
                                                    Name = 'Competitor Intelligence Test 1',
                                                    Type__c = 'Intelligence'
                                                    );
        insert newCompetitorIntelligence;
	}
	
    static testMethod void autoCreateChatterPostTest() {
        //call test data creation method
        createTestData();
        //test execution begin
        Test.StartTest();
        List<Competitor_Intelligence__c> cList = new List<Competitor_Intelligence__c>();
        cList.add(newCompetitorIntelligence);
        CompetitorIntelligenceTriggerHandler.autoCreateChatterPost(cList);
        
        Test.StopTest();
        
        
    }
}