force-app/main/default/objects/ChatterPostGroupMention__c/ChatterPostGroupMention__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The  Chatter groups that will be mentioned on  the new Chatter post for every new Competitor Intelligence Record

To get the ID of the Chatter Group, go to User menu-&gt; Developer Console -&gt; Query Editor tab -&gt; Enter &quot;SELECT id, name  FROM CollaborationGroup&quot; -&gt; Click Execute</description>
    <label>ChatterPostGroupMention</label>
</CustomObject>

force-app/main/default/objects/ChatterPostGroupMention__c/fields/Competitive_Intelligence_Type__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Intelligence_Type__c</fullName>
    <label>Competitive Intelligence Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_Intelligence__c/Competitor_Intelligence__c.object-meta.xml
<CustomObject>
    <label>Competitor Intelligence</label>
    <nameField>
        <label>Competitor Intelligence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Intelligence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Intelligence__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Intelligence</relationshipLabel>
    <relationshipName>Competitor_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Intelligence__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisitions / Joint Ventures</fullName>
            </value>
            <value>
                <fullName>Hot Topic</fullName>
            </value>
            <value>
                <fullName>Intelligence</fullName>
            </value>
            <value>
                <fullName>Org Resources Change</fullName>
            </value>
            <value>
                <fullName>Rumor</fullName>
            </value>
            <value>
                <fullName>Technoology Trend / Capability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CITriggerHandler_Test.cls
/*
*    @description:    Test class for CompetitorIntelligenceTriggerHandler.
*    @author:         Sharee Mae Ingatan (sharee.mae.r.ingatan@accenture.com)
*    @createddate:    April 20, 2016
*/
@isTest
public class CITriggerHandler_Test {
	private CITriggerHandler_Test(){}
  @IsTest(SeeAllData=true)
    public static void autoCreateChatterPostTest() {
      Test.startTest();
        RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
        Account newCompetitor = new Account(RecordTypeId = competitorRT.Id,
                          Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                          );
        insert newCompetitor;
        
        CollaborationGroup newChatterGroup = new CollaborationGroup(Name = 'Chatter Group Test 1',
                                      CollaborationType = 'Public'
                                      );
        insert newChatterGroup;
        
        ChatterPostGroupMention__c chatterGroupSetting = new ChatterPostGroupMention__c(Name = 'Chatter Group Setting Test 1',
                                                Group_Id__c = newChatterGroup.Id,
                                                Competitive_Intelligence_Type__c = 'Intelligence'
                                                );
        insert chatterGroupSetting;
        
        Competitor_Intelligence__c newCompetitorIntelligence = new Competitor_Intelligence__c(Competitor__c = newCompetitor.Id,
                                                    Name = 'Competitor Intelligence Test 1',
                                                    Type__c = 'Intelligence'
                                                    );
        insert newCompetitorIntelligence;
        
      Test.stopTest();
    }
}