force-app/main/default/objects/AccountPlan__c/AccountPlan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Account,Commercial Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <description>Link to Quip Account Plan Document</description>
    <label>Account Plan</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusiness</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Customer_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/AccountPlanDetail__c.object-meta.xml
<CustomObject>
    <label>Account Plan Detail</label>
    <nameField>
        <displayFormat>APD{000000}</displayFormat>
        <label>Account Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPlanDetail__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Customer_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Strategic_Objective__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Objective</label>
    <referenceTo>StrategicObjective__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Profiles</relationshipLabel>
    <relationshipName>Customer_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brands</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusiness</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/CustomerDescription__c.field-meta.xml
<CustomField>
    <fullName>CustomerDescription__c</fullName>
    <label>Customer Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/ProductLines__c.field-meta.xml
<CustomField>
    <fullName>ProductLines__c</fullName>
    <description>This may be defined as Picklist or Lookup based on Cargill discussion around Product Hierarachy.</description>
    <label>ProductLines</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is created as a part of Cargill Leap Project-IDCTask-0000000162</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ideation</fullName>
            </value>
            <value>
                <fullName>Explore</fullName>
            </value>
            <value>
                <fullName>Feasibility</fullName>
            </value>
            <value>
                <fullName>Develop</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Implement</fullName>
            </value>
            <value>
                <fullName>Measure</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Go</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Strategic Objective - Commercial Account</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  StartDate__c &gt; TODAY(),
       &quot;Pending&quot;,
       IF(OR(EndDate__c &gt; TODAY(), ISNULL(EndDate__c),ISBLANK(EndDate__c)),
       &quot;Active&quot;,
       &quot;Expired&quot;
  ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountPlanPDFGenerate_Extension.cls
/**
   @Author - Rajeshwari M
   @name -  AccountPlanPDFGenerate_Extension 
   @CreateDate - 
   @Description - This Apex class is extension for VF Page AccountPlanPDFGenerate which displays AccountPlan's related objects information-
   @               1.Customer Profiles 2.Customer Team 3.Contact 4.Opportunities 5.Projects 6.Strategic Objectives
   @Revision- 1.0
*/
public with sharing class AccountPlanPDFGenerate_Extension {
    
    public AccountPlan__c record{get; set;}
    public List<AccountPlanDetail__c> apdcontact{get; set;}
    public List<AccountPlanDetail__c> apdProjects{get; set;}
    public List<AccountPlanDetail__c> apdSO{get; set;}
    public List<AccountPlanDetail__c> apdOpp{get; set;}
    public List<AccountPlan__c> accPlanCustomerProfile{get; set;}
    public Boolean isCustomProf{get; set;}
    public List<AccountTeamMember> teams{get; set;}
    public DateTime gmtDate{get; set;}
    public String estDate{get; set;}
    private final static string TIMEFORMAT = 'EEEE,MMMM dd,yyyy hh:mm:ss zzzz';
    private final static string TIMEZONE = 'America/New_York';
    
    /*
    @methodname-AccountPlanPDFGenerate_Extension
    @aurguments-controller
    @description-standard controller
    */
    public AccountPlanPDFGenerate_Extension(ApexPages.StandardController controller) {
        record=(AccountPlan__c)controller.getRecord(); 
        gmtDate = system.now();
        estDate=gmtDate.format(TIMEFORMAT,TIMEZONE);
        getRelatedObjects(record);
    }
    
    /*
    @methodname-getRelatedObjects
    @aurguments-accPlan
    @description-Fetches related data of Account Plan
    */
    public void getRelatedObjects(AccountPlan__c accPlan){
        try{
        List<AccountPlanDetail__c> accPlanDetailList = new List<AccountPlanDetail__c>();
        apdcontact = new List<AccountPlanDetail__c>();
        apdProjects= new List<AccountPlanDetail__c>();
        apdSO= new List<AccountPlanDetail__c>();
        apdOpp= new List<AccountPlanDetail__c>();
        teams=new List<AccountteamMember>();
        accPlanCustomerProfile = new List<AccountPlan__c>();
        
        
        if(accPlan.Id!=null){
        AccountPlan__c aPlan= [Select id,Account__c,
                               Customer_Profile__c,Customer_Profile__r.CustomerDescription__c,Customer_Profile__r.Brands__c,Customer_Profile__r.Business__c,Customer_Profile__r.ProductLines__c 
                               FROM AccountPlan__c WHERE id=: accPlan.Id LIMIT 1];
        
        if(aPlan.Customer_Profile__c!=null){
            accPlanCustomerProfile .add(aPlan);
        }
        
        Account acc=[Select id,(Select id,CustomerDescription__c,Brands__c,Business__c,ProductLines__c FROM Customer_Profiles__r LIMIT 1),(Select User.Name,User.Cargill_Business_Unit__c,TeamMemberRole FROM AccountTeamMembers LIMIT 10000) FROM Account WHERE id=:aPlan.Account__c LIMIT 1];
        if(acc.AccountTeamMembers!=null && !acc.AccountTeamMembers.isEmpty()){
            teams = acc.AccountTeamMembers;
        }
    
        accPlanDetailList = [Select id,Name,
                    Contact__c,Contact__r.Name,Contact__r.Title,Contact__r.Owner.Name,Contact__r.Role__c,Contact__r.ReportsTo.Name,
                    Project__c,Project__r.Name,Project__r.RecordType.Name,Project__r.Stage__c,Project__r.Phase__c,
                    Strategic_Objective__c,Strategic_Objective__r.CustomerProfile__r.Name,Strategic_Objective__r.Status__c,Strategic_Objective__r.StartDate__c,Strategic_Objective__r.EndDate__c,
                    Opportunity__c,Opportunity__r.Name,Opportunity__r.StageName,Opportunity__r.Probability,Opportunity__r.Amount,Opportunity__r.CloseDate,Opportunity__r.Description
                    FROM AccountPlanDetail__c WHERE Account_Plan__c =: accPlan.Id LIMIT 10000];
                    
        
        if(!accPlanDetailList.isEmpty() && accPlanDetailList!=null){
            For(AccountPlanDetail__c accPlanDetail : accPlanDetailList){
               if(accPlanDetail.Project__c!=null){
                   apdProjects.add(accPlanDetail);
               }
               if(accPlanDetail.Strategic_Objective__c!=null){
                   apdSO.add(accPlanDetail);
               }
               if(accPlanDetail.Opportunity__c!=null){
                   apdOpp.add(accPlanDetail);
               }
               if(accPlanDetail.Contact__c!=null){
                   apdcontact.add(accPlanDetail);    
               }
               
           }
         
      
        }
    }
        }catch(Exception Ex){
            Throw Ex;
        }
 
}
}