force-app/main/default/objects/AccountPlan__c/AccountPlan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Account,Commercial Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Business2__c.field-meta.xml
<CustomField>
    <fullName>Business2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is created as a part of Cargill Leap Project</description>
    <label>Business</label>
    <referenceTo>BusinessDetail__c</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusiness</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Customer_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>Plan_Year__c</fullName>
    <label>Plan Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
                <default>true</default>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/BusinessDetail__c.object-meta.xml
<CustomObject>
    <label>Business Detail</label>
    <nameField>
        <label>Business Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Profiles</relationshipLabel>
    <relationshipName>Customer_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusiness</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Market_Channel__c.field-meta.xml
<CustomField>
    <fullName>Market_Channel__c</fullName>
    <formula>Text(Account__r.Market_Channel__c)</formula>
    <label>Market Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is created as a part of Cargill Leap Project-IDCTask-0000000162</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectProduct__c/ProjectProduct__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <displayFormat>ProjProd{000000}</displayFormat>
        <label>Project Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectProduct__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Confectionery</fullName>
            </value>
            <value>
                <fullName>Convenience foods</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Fruit</fullName>
            </value>
            <value>
                <fullName>Infant &amp; baby food</fullName>
            </value>
            <value>
                <fullName>Meat</fullName>
            </value>
            <value>
                <fullName>Personal care</fullName>
            </value>
            <value>
                <fullName>Pet food</fullName>
            </value>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Snacks &amp; cereals</fullName>
            </value>
            <value>
                <fullName>Feed</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Food ingredients</fullName>
            </value>
            <value>
                <fullName>Test 2</fullName>
                <isActive>false</isActive>
                <label>Test 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectProduct__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Products</relationshipLabel>
    <relationshipName>Project_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectProductHandler_Test.cls
/**
 Test class to cover functionality of class: ProjectProductHandler
 */
@isTest
private class ProjectProductHandler_Test {

    static testMethod void projectProductHandlerTest() {
       
		//insert test data
        Map<String,Schema.RecordTypeInfo> recordTypeMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingCity = 'Test';
        acc.BillingState = 'Iowa';
        acc.BillingStreet = 'Test';
        acc.BillingPostalCode = 'Test';
        acc.ShippingCity = 'Test';
        acc.ShippingState = 'Iowa';
        acc.ShippingStreet = 'Test';
        acc.ShippingPostalCode = 'Test';
        acc.RecordTypeId= recordTypeMap.get('Global Account').getRecordTypeId();
        acc.Market_Channel__c='Retail Channel';
        insert(acc);
        
        Account acc1 = new Account();
        acc1.Name = 'Test';
        acc1.BillingCity = 'Test';
        acc1.BillingState = 'Iowa';
        acc1.BillingStreet = 'Test';
        acc1.BillingPostalCode = 'Test';
        acc1.ShippingCity = 'Test';
        acc1.ShippingState = 'Iowa';
        acc1.ShippingStreet = 'Test';
        acc1.ShippingPostalCode = 'Test';
        acc1.RecordTypeId= recordTypeMap.get('Sold To').getRecordTypeId();
        acc1.Is_Universal__c = TRUE;
        acc1.Market_Channel__c='Retail Channel';
        insert(acc1);
        
        Opportunity opp = new Opportunity();
        opp.Name='Test'; 
        opp.NextStep='test';                                   
        opp.CloseDate = System.today();                                    
        opp.AccountId=acc.id; 
        opp.StageName='Closed Won - One Time'; 
        opp.Probability=100;
        insert(opp);
        
        Business__c BUnit = new Business__c();
        BUnit.Name = 'Teat';
        BUnit.BusinessUnitAlias__c = 'GTM Corp Accts';
        BUnit.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        BUnit.CargillGroup__c = 'GoToMarket (GTM)';
        insert(BUnit);
        
        BusinessDetail__c BDetails = new BusinessDetail__c();
        BDetails.Account__c = acc.Id;
        BDetails.BusinessUnit__c = BUnit.Id;
        BDetails.Status__c = 'Active';
        insert(BDetails);
        
				
		Product2 prd1 = new Product2 (Name='Test Product Entry 1',Description='Test Product Entry 1',productCode = 'ABC', isActive = true,Business__c='Commercial Excellence NA',Product_Deployment__c='Placeholder');
		insert prd1;
		
		
		PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=Test.getStandardPricebookId(),UnitPrice=50, isActive=true);
		insert pbe1;
		
				
		OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=opp.id,PriceBookEntryID=pbe1.id, quantity=4, totalprice=200);
		insert lineItem1;
                 
        
        CustomerProfile__c cProfile = new CustomerProfile__c();
        cProfile.Account__c = acc.Id;
        insert cProfile;
        
        AccountPlan__c accPlan = new AccountPlan__c();
        accPlan.Account__c = acc1.id;
        accPlan.Business2__c = BDetails.id;
        accPlan.Customer_Profile__c = cProfile.id;
        accPlan.Plan_Year__c = '2017 Fiscal Year';
        insert accPlan;
        
        Project__c project = new Project__c();
        project.Account__c = acc.id;
        project.AccountPlan__c = accPlan.id;
        project.Business__c = BUnit.id;
        project.Opportunity__c = opp.id;
        insert project;
        
        ProjectProduct__c projProduct = new ProjectProduct__c();
        projProduct.Project__c = project.id;
        projProduct.Product__c = prd1.id;
        projProduct.Category__c = 'Bakery';
        //test execution begin
        Test.StartTest();
        //test for before insert trigger method
        insert projProduct;
        
        system.assertEquals(projProduct.Category__c,'Bakery');
        
        projProduct.Category__c = 'Beverage';
        update projProduct;
        
        system.assertEquals(projProduct.Category__c,'Beverage');
        
        Test.StopTest();
        
        
    }
}