force-app/main/default/objects/AccountPlan__c/AccountPlan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPG_AddAccountPlanDetailController_Test.cls
/**
Class Name: CPG_AddAccountPlanDetailController_Test
Created Date: Oct-15-2017
Created By: Cognizant
This class is  the test class for controller class- CPG_AddAccountPlanDetailController
**/
@isTest
public class CPG_AddAccountPlanDetailController_Test{
@testSetup
static void setup(){
    //creating test running user
    user u=CPG_TestFactory_Util.createTestUser('System Administrator');
    system.runAs(u){
        //create Account
        list<Account> acc=CPG_TestFactory_Util.createTestAccounts(1); 
        //Create Opportunity    
        list<opportunity> opplist=CPG_TestFactory_Util.createTestOpportunity(1,acc);
        system.assertEquals(opplist[0].Volume__c, 100);    
        //create Customer Profile
        list<CustomerProfile__c> custProf = CPG_TestFactory_Util.createTestCustomerProfiles(1,acc);
        //Create Strategic Objective
        list<StrategicObjective__c> stratObj = CPG_TestFactory_Util.createTestStrategicObjectives(1, custProf);
        //Create Account Plan
        list<AccountPlan__c> accPlan = CPG_TestFactory_Util.createTestAccountPlan(1, acc);          
    }
}
@isTest
static void testAccountPlanDetailController(){
    list<AccountPlan__c> accPlan = [select id from accountPlan__c limit 1];
    list<StrategicObjective__c> lstStrat = CPG_AddAccountPlanDetailController.getStratObjectives(accPlan[0].id);
    System.assertNotEquals(lstStrat.size(),0);
    
    list<Opportunity> lstOpp = CPG_AddAccountPlanDetailController.addAPobjectives(new list<id> {lstStrat[0].id}, accPlan[0].id);
    System.assertNotEquals(lstOpp.size(),0); 
    
    CPG_AddAccountPlanDetailController.saveAP(new list<id> {lstOpp[0].id} , accPlan[0].id, null);
}


}