force-app/main/default/objects/Competitor_Junction__c/Competitor_Junction__c.object-meta.xml
<CustomObject>
    <description>US 19, 20, 22, 13, 4, 41</description>
    <label>Competitor Junction</label>
    <nameField>
        <label>Competitor Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Junction__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Concorrente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Customers</relationshipLabel>
    <relationshipName>Competitor_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Junction__c/fields/Competitor_Performance_Trend__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Performance_Trend__c</fullName>
    <label>Competitor Performance Trend</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Up</fullName>
            </value>
            <value>
                <fullName>Down</fullName>
            </value>
            <value>
                <fullName>Flat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Junction__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Competitors</relationshipLabel>
    <relationshipName>Competitor_Junctions1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CompetitorPerformanceTrendRange__c/CompetitorPerformanceTrendRange__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Competitor Performance Trend Range</label>
</CustomObject>

force-app/main/default/objects/CompetitorPerformanceTrendRange__c/fields/DOWN_Range__c.field-meta.xml
<CustomField>
    <fullName>DOWN_Range__c</fullName>
    <label>DOWN Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CompetitorPerformanceTrendRange__c/fields/UP_Range__c.field-meta.xml
<CustomField>
    <fullName>UP_Range__c</fullName>
    <label>UP Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CompetitorJunctionTriggerHandler_Test.cls
/*
*    @description:    Test class for CompetitorJunctionTriggerHandler.
*    @author:         Sharee Mae Ingatan (sharee.mae.r.ingatan@accenture.com)
*    @createddate:    April 20, 2016
*/
@isTest
public class CompetitorJunctionTriggerHandler_Test {
    
    public static testMethod void countCustomerCompetitors_Test() {
        Test.startTest();
            //RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Map<String,Schema.RecordTypeInfo> recordTypeMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
            Account newCompetitor = new Account(RecordTypeId = recordTypeMap.get('Competitor').getRecordTypeId(),
                                                Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCompetitor;
            
            //RecordType customerRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCustomer = new Account(RecordTypeId = recordTypeMap.get('Competitor').getRecordTypeId(),
                                                Name = 'newCustomer Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCustomer;
            
            Competitor_Junction__c newCompetitorJunction = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id
                                                                                        );
            insert newCompetitorJunction;
            
            
            
            //calling handler methods
            List<Competitor_Junction__c> CJList = new List<Competitor_Junction__c>();
            CJList.add(newCompetitorJunction);
           
            CompetitorJunctionTriggerHandler.countCustomerCompetitors(CJList);
            
        Test.stopTest();
    }
    
    //test 50/50 with range set and lower Up Range
    public static testMethod void updateCompetitorPerformanceTrend_Test1() {
        Test.startTest();
            RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCompetitor = new Account(RecordTypeId = competitorRT.Id,
                                                Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCompetitor;
            
            RecordType customerRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCustomer = new Account(RecordTypeId = customerRT.Id,
                                                Name = 'newCustomer Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCustomer;
            
            CompetitorPerformanceTrendRange__c rangeSetting = new CompetitorPerformanceTrendRange__c(UP_Range__c = 80,
                                                                                                        DOWN_Range__c = 60,
                                                                                                        Name = 'Range Setting Test 1'
                                                                                                        );
            insert rangeSetting;
            
            Competitor_Junction__c newCompetitorJunction = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c = 'Up'
                                                                                        );
            insert newCompetitorJunction;
            
            Competitor_Junction__c newCompetitorJunction2 = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c = 'Down'
                                                                                        );
            insert newCompetitorJunction2;
            
             //calling handler methods
            List<Competitor_Junction__c> CJList = new List<Competitor_Junction__c>();
            CJList.add(newCompetitorJunction);
            CompetitorJunctionTriggerHandler.updateCompetitorPerformanceTrend(CJList);
            
        Test.stopTest();
    }
    
    //test 50/50 with default range
    public static testMethod void updateCompetitorPerformanceTrend_Test2() {
        Test.startTest();
            RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCompetitor = new Account(RecordTypeId = competitorRT.Id,
                                                Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCompetitor;
            
            RecordType customerRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCustomer = new Account(RecordTypeId = customerRT.Id,
                                                Name = 'newCustomer Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCustomer;
            
            Competitor_Junction__c newCompetitorJunction = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c = 'Up'
                                                                                        );
            insert newCompetitorJunction;
            
            Competitor_Junction__c newCompetitorJunction2 = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c = 'Down'
                                                                                        );
            insert newCompetitorJunction2;
        Test.stopTest();
    }
    
    //test 50/50 with range set and greater Up Range
    public static testMethod void updateCompetitorPerformanceTrend_Test3() {
        Test.startTest();
            RecordType competitorRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCompetitor = new Account(RecordTypeId = competitorRT.Id,
                                                Name = 'Competitor Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCompetitor;
            
            RecordType customerRT = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Competitor'];
            Account newCustomer = new Account(RecordTypeId = customerRT.Id,
                                                Name = 'newCustomer Test 1',Market_Channel__c='Retail Channel'
                                                );
            insert newCustomer;
            
            CompetitorPerformanceTrendRange__c rangeSetting = new CompetitorPerformanceTrendRange__c(UP_Range__c = 40,
                                                                                                        DOWN_Range__c = 30,
                                                                                                        Name = 'Range Setting Test 1'
                                                                                                        );
            insert rangeSetting;
            
            Competitor_Junction__c newCompetitorJunction = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c = 'Up'
                                                                                        );
            insert newCompetitorJunction;
            
            Competitor_Junction__c newCompetitorJunction1 = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id,
                                                                                        Competitor_Performance_Trend__c='Up'
                                                                                        );
            insert newCompetitorJunction1;
            
            Competitor_Junction__c newCompetitorJunction2 = new Competitor_Junction__c(Name = 'Competitor Junction Test 1',
                                                                                        Customer__c = newCustomer.Id,
                                                                                        Competitor__c = newCompetitor.Id
                                                                                        );
            insert newCompetitorJunction2;
            
            //calling handler methods
            List<Competitor_Junction__c> CJList = new List<Competitor_Junction__c>();
            CJList.add(newCompetitorJunction);
            CJList.add(newCompetitorJunction1);
            CJList.add(newCompetitorJunction2);
            CompetitorJunctionTriggerHandler.updateCompetitorPerformanceTrend(CJList);
            
        Test.stopTest();
    }
}