force-app/main/default/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <description>Used for Avenger Protein</description>
    <label>New Product Collection Form</label>
    <nameField>
        <label>Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Product Collection Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Request__c/fields/Pricing_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Due_Date__c</fullName>
    <description>Pricing Due Date</description>
    <label>Pricing Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Pricing_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Timeframe__c</fullName>
    <label>Pricing Timeframe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Sent_to_Pricer__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Pricer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sent to Pricer</description>
    <label>Sent to Pricer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Accepted by BM</fullName>
            </value>
            <value>
                <fullName>Rejected by BM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Protein_SendToPricerHelper.cls
/*
Author: Latha A
Description : This is a helper class for Protein_SendToPricerController class
Method Name : updateEmailMessageBeforeInsert      

*/

public with sharing class Protein_SendToPricerHelper {

    public static boolean validateSendToPricer(Product_Request__c pr,Boolean isSentToPricer)
    {
        if(pr.Sent_to_Pricer__c == true){
           return (isSentToPricer=true);   
                     
        }
        else{
            return false;  //validateFieldCheckOne(pr,isFieldCheck);
        } 
               
    }
    public static boolean validateFieldCheckOne(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c == null && pr.Pricing_Timeframe__c == null && pr.Status__c != System.Label.Protein_SentPricerStatus ){
            return (isFieldCheck = true);               
        }
        else{
             return validateFieldCheckTwo(pr,isFieldCheck);
        } 
    }
    private static boolean validateFieldCheckTwo(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c == null && pr.Pricing_Timeframe__c != null && pr.Status__c != System.Label.Protein_SentPricerStatus ){
              return (isFieldCheck = true);          
        }
        else{
           return validateFieldCheckThree(pr,isFieldCheck);
        }
    }
    private static boolean validateFieldCheckThree(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c != null && pr.Pricing_Timeframe__c == null && pr.Status__c != System.Label.Protein_SentPricerStatus ){
              return (isFieldCheck = true);               
        }
        else{
            return validateFieldCheckFour(pr,isFieldCheck);
        }
    }
    private static boolean validateFieldCheckFour(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c != null && pr.Pricing_Timeframe__c != null && pr.Status__c != System.Label.Protein_SentPricerStatus ){
                return (isFieldCheck = true);               
        }
        else{
            return validateFieldCheckFive(pr,isFieldCheck);
        }
    }
    private static boolean validateFieldCheckFive(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c == null && pr.Pricing_Timeframe__c == null && pr.Status__c == System.Label.Protein_SentPricerStatus ){
              return (isFieldCheck = true);            
        }
        else{
             return validateFieldCheckSix(pr,isFieldCheck);
        }
    }
    private static boolean validateFieldCheckSix(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c != null && pr.Pricing_Timeframe__c == null && pr.Status__c == System.Label.Protein_SentPricerStatus ){
               return (isFieldCheck = true);               
        }
        else{
             return validateFieldCheckSeven(pr,isFieldCheck);
        }
    }
    private static boolean validateFieldCheckSeven(Product_Request__c pr,Boolean isFieldCheck)
    {
        if(pr.Sent_to_Pricer__c == false && pr.Pricing_Due_Date__c == null && pr.Pricing_Timeframe__c != null && pr.Status__c == System.Label.Protein_SentPricerStatus ){
               return (isFieldCheck = true);              
        }
        return false;
    } 

}