force-app/main/default/objects/PROS_Log__c/PROS_Log__c.object-meta.xml
<CustomObject>
    <label>PROS Log</label>
    <nameField>
        <label>PROS Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PROS_Log__c/fields/BatchID__c.field-meta.xml
<CustomField>
    <fullName>BatchID__c</fullName>
    <label>BatchID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PROS_Log__c/fields/PROS_Quote__c.field-meta.xml
<CustomField>
    <fullName>PROS_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PROS Quote</label>
    <referenceTo>CameleonCPQ__Quote__c</referenceTo>
    <relationshipLabel>PROS Logs</relationshipLabel>
    <relationshipName>PROS_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PROS_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PROS_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RECORD</fullName>
            </value>
            <value>
                <fullName>INFORMATION</fullName>
            </value>
            <value>
                <fullName>CONFIG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>FATAL</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProsLogger.cls
public class ProsLogger 
{
	private List<sObject> prosLogList;
    
    public ProsLogger()
    {
        prosLogList = new List<sObject>();
    }
    
    public virtual ProsLogger Log(
        String batchId, 
        ProsUtils.LogStatus status, 
        ProsUtils.LogType type, 
        String message, 
        DateTime startDate, 
        DateTime endDate, 
        String quoteId, 
        String externalId)
    {  
        PROS_Log__c prosLog = new PROS_Log__c();
        prosLog.put('BatchID__c', batchId);
        prosLog.put('Status__c', status.Name());
        prosLog.put('Type__c', type.Name());
        prosLog.put('Message__c', message);
        prosLog.put('StartDate__c', startDate);
        prosLog.put('EndDate__c', endDate);   
        prosLog.put('PROS_Quote__c', quoteId);
        prosLog.put('External_Id__c', externalId);
        prosLogList.add(prosLog);
        return this;
    }
    
    public virtual ProsLogger Log(
        String batchId, 
        ProsUtils.LogStatus status, 
        ProsUtils.LogType type, 
        String message, 
        DateTime startDate, 
        DateTime endDate)
    {  
        
        return Log(batchId, status, type, message, startDate, endDate, null, null);
    }
    
    public virtual ProsLogger Log(
        String batchId, 
        ProsUtils.LogStatus status, 
        ProsUtils.LogType type, 
        String message)
    {  
        Datetime now = System.now();
        return Log(batchId, status, type, message, now, now);
    }
    
    public virtual ProsLogger Log(
        ProsUtils.LogStatus status, 
        ProsUtils.LogType type, 
        String message, 
        DateTime startDate, 
        DateTime endDate)
    {          
        return Log(null, status, type, message, startDate, endDate);
    }
    
    public virtual ProsLogger Log(
        ProsUtils.LogStatus status,
        ProsUtils.LogType type, 
        String message)
    {  
        Datetime now = System.now();
        return Log(status, type, message, now, now);
    }
    
    public ProsLogger Error(String message)
    {
        return Log(ProsUtils.LogStatus.FAILURE, ProsUtils.LogType.ERROR, message);
    }
    
    public ProsLogger Info(String message)
    {
        return Log(ProsUtils.LogStatus.SUCCESS, ProsUtils.LogType.INFORMATION, message);
    }
    
    public void Save()
    {        
        try
        {
            if (prosLogList.size() > 0)
            {
                insert prosLogList;
        		prosLogList.clear();
            }
        }
        catch (Exception e)
        {
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        }
    }
}