force-app/main/default/objects/CustomerMeetingReportOpp__c/CustomerMeetingReportOpp__c.object-meta.xml
<CustomObject>
    <label>Customer Meeting Report Opp</label>
    <nameField>
        <displayFormat>CMROpp{000000}</displayFormat>
        <label>Customer Meeting Report Opp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Meeting Report Opps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerMeetingReportOpp__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Meeting Report</relationshipLabel>
    <relationshipName>Customer_Meeting_Report_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Protein_CustMtgReportOppTriggerHandler.cls
public with sharing class Protein_CustMtgReportOppTriggerHandler {
    public static void updateNextStepsPresenceCheckboxInOppty(List<CustomerMeetingReportOpp__c> lstCMROs) {
        Set<Id> oppIDs =  new Set<Id>();
        //Add the Opportunity IDs to oppIDs set.
        for(CustomerMeetingReportOpp__c cmro : lstCMROs)
        {
            oppIDs.add(cmro.Opportunity__c);
        }
        //Get a map of the Opportunities with the number of CMROs.
        Map<Id,Opportunity> mapOpps = new Map<Id,Opportunity>([SELECT Id, Count_of_CMROs__c FROM Opportunity WHERE Id IN :oppIDs]);
        
        //Query the Opps and the related CMROs & add the size of the CMROs to the Count_of_CMROs__c field in opp.
        for(Opportunity opp : [SELECT Id, Name, Count_of_CMROs__c, (SELECT Id FROM Customer_Meeting_Report_Opps__r) FROM Opportunity WHERE Id IN :oppIDs]) {
            mapOpps.get(opp.Id).Count_of_CMROs__c = opp.Customer_Meeting_Report_Opps__r.size();
        }
        System.debug('mapOpps: '+mapOpps);
        try{
            if(!mapOpps.isEmpty())
            {
                update mapOpps.values();
            }
        }
        catch(dmlException ex) {
            System.debug('Error message: ' +ex.getDmlMessage(0));
        }
    }

}