force-app/main/default/objects/CPQQuoteLineItem__c/CPQQuoteLineItem__c.object-meta.xml
<CustomObject>
    <label>PROS Quote Line Item</label>
    <nameField>
        <label>Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQQuoteLineItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCode</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PROS Quote Line Items</relationshipLabel>
    <relationshipName>PROS_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateproductcodeHandler.cls
/*@Author -Apps-AMS-CustomerFacing-Global
@date - 11-13-2018
purpose:The triggerhandler is used for updating the productcode in quotelineitem*/

public class updateproductcodeHandler{
    
    public static void updateproductcode(List<CPQQuoteLineItem__c > cpqLineItemlst)
    {
        Map<String, Id> products = new Map<String, Id>();
        for(CPQQuoteLineItem__c record: cpqLineItemlst) {
            products.put(record.Product_Code__c, null);
        }
        // Query for record Ids
        for(Product2 record: [SELECT Name FROM Product2 WHERE Name = :products.keySet()]) {
            products.put(record.Name, record.Id);
        }
        // Update Trigger.new with queried values
        for(CPQQuoteLineItem__c record: cpqLineItemlst) {
            record.ProductCode__c = products.get(record.Product_Code__c);
        }}
    
}