force-app/main/default/objects/CreditLimit__c/CreditLimit__c.object-meta.xml
<CustomObject>
    <label>Credit Limit</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Credit Limit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Limits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditLimit__c/fields/CommercialAccount__c.field-meta.xml
<CustomField>
    <fullName>CommercialAccount__c</fullName>
    <label>Commercial Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CommercialAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Limits</relationshipLabel>
    <relationshipName>Credit_Limits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/CreditLimit__c.field-meta.xml
<CustomField>
    <fullName>CreditLimit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Limit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Commercial_Account__c</field>
            <operation>equals</operation>
            <valueField>CreditLimit__c.CommercialAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CreditLimit__c</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AVX_CreditLimitTriggerHelper_cls.cls
/**
**************************************************************************************************************
* @company          Avanxo Brasil
* @author           Igor Novaes href=<igor.novaes@globant.com>
* @project          EXODUS - CPLA Cargill
* @name             AVX_CreditLimit_tgr
* @description      Helper for the trigger AVX_CreditLimit_tgr
* @dependencies     none
* @changes (Version)
* --------   ---   ----------   ---------------------------   ------------------------------------------------
*            No.   Date         Author                        Description
* --------   ---   ----------   ---------------------------   ------------------------------------------------
* @version   1.0   2020-02-03   Igor Novaes.                  Initial version.
**************************************************************************************************************
**/

public class AVX_CreditLimitTriggerHelper_cls {

    public static void relateShipToAndCreditLimit(List<CreditLimit__c> lstContext) {
        
        Map<Id,Id> mapCreditLimitByCommercialAcc = new Map<Id,Id>();
        for(CreditLimit__c objCreditLimit : lstContext){
            if(objCreditLimit.IsActive__c){
                mapCreditLimitByCommercialAcc.put(objCreditLimit.CommercialAccount__c, objCreditLimit.Id);
            }
        }

        List<Ship_To__c> lstShipTo = [SELECT Id,Commercial_Account__c, CreditLimit__c FROM Ship_To__c WHERE Commercial_Account__c IN :mapCreditLimitByCommercialAcc.keySet()];
        if(lstShipTo.isEmpty()) return;

        List<Ship_To__c> lstShipTo_Update = new List<Ship_To__c>();
        
        for(Ship_To__c objShipTo : lstShipTo){
            if(objShipTo.CreditLimit__c != mapCreditLimitByCommercialAcc.get(objShipTo.Commercial_Account__c)){
                objShipTo.CreditLimit__c = mapCreditLimitByCommercialAcc.get(objShipTo.Commercial_Account__c);
                lstShipTo_Update.add(objShipTo);
            }
        }

        if(lstShipTo_Update != null && !lstShipTo_Update.isEmpty()){
            update lstShipTo_Update; 
        }
    }
}