force-app/main/default/objects/AccountView__c/AccountView__c.object-meta.xml
<CustomObject>
    <label>Account Team View</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>AccountTeamView Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team View</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountView__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team View</relationshipLabel>
    <relationshipName>AccountViews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Account_Access__c.field-meta.xml
<CustomField>
    <fullName>Account_Access__c</fullName>
    <label>Account Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Account_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Team_Role__c</fullName>
    <label>Account Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Qualifier</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Corporate Account Lead</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Technical Service Lead</fullName>
            </value>
            <value>
                <fullName>Technical Services Engineer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipName>Account_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Business_Detail__c.field-meta.xml
<CustomField>
    <fullName>Business_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NOT CURRENTLY USED</description>
    <label>Business Detail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>BusinessDetail__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessDetail__c</referenceTo>
    <relationshipLabel>Account Team View</relationshipLabel>
    <relationshipName>Account_Team_View</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Case_Access__c.field-meta.xml
<CustomField>
    <fullName>Case_Access__c</fullName>
    <label>Case Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/Opportunity_Access__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Access__c</fullName>
    <label>Opportunity Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountView__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountViews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/BusinessUnitAlias__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitAlias__c</fullName>
    <label>Business Alias</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargillBusinessAlias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillEnterprise__c.field-meta.xml
<CustomField>
    <fullName>CargillEnterprise__c</fullName>
    <label>Cargill Enterprise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Enterprise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/fields/CargillGroup__c.field-meta.xml
<CustomField>
    <fullName>CargillGroup__c</fullName>
    <label>Cargill Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cargill_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/BusinessDetail__c.object-meta.xml
<CustomObject>
    <label>Business Detail</label>
    <nameField>
        <label>Business Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipLabel>Business Details</relationshipLabel>
    <relationshipName>Business_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessDetail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Cargill_Enterprise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FoodIngredientsBioIndustrialFIBI</fullName>
        <label>Food Ingredients &amp; Bio Industrial (FIBI)</label>
    </customValue>
    <customValue>
        <fullName>Animal Proteins &amp; Salt (APS)</fullName>
        <isActive>false</isActive>
        <label>Animal Proteins &amp; Salt (APS)</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Cargill Enterprise</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cargill_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>GlobalEdibleOilSolutionsGEOS</fullName>
        <isActive>false</isActive>
        <label>Global Edible Oil Solutions (GEOS)</label>
    </customValue>
    <customValue>
        <fullName>Starches &amp; Sweeteners (SS)</fullName>
        <isActive>false</isActive>
        <label>Starches &amp; Sweeteners (SS)</label>
    </customValue>
    <customValue>
        <fullName>Asia Pacific &amp; Malt</fullName>
        <isActive>false</isActive>
        <label>Asia Pacific &amp; Malt</label>
    </customValue>
    <customValue>
        <fullName>Salt</fullName>
        <isActive>false</isActive>
        <label>Salt</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>GoToMarket (GTM)</fullName>
        <isActive>false</isActive>
        <label>GoToMarket (GTM)</label>
    </customValue>
    <customValue>
        <fullName>Cocoa &amp; Chocolate (CC)</fullName>
        <isActive>false</isActive>
        <label>Cocoa &amp; Chocolate (CC)</label>
    </customValue>
    <masterLabel>Cargill Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargillBusinessAlias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GTM Corp Accts</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GTM SS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS NA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Europe</fullName>
    </customValue>
    <customValue>
        <fullName>CIS</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS SA</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS Venezuela</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS India</fullName>
    </customValue>
    <customValue>
        <fullName>GEOS AP</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>SSNA</fullName>
    </customValue>
    <customValue>
        <fullName>SSE</fullName>
    </customValue>
    <customValue>
        <fullName>CTS</fullName>
    </customValue>
    <customValue>
        <fullName>SSSA</fullName>
    </customValue>
    <customValue>
        <fullName>CF METNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC</fullName>
    </customValue>
    <customValue>
        <fullName>CCCNA</fullName>
    </customValue>
    <customValue>
        <fullName>CCC Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>ROAP</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S China</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;S SE Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Toshoku</fullName>
    </customValue>
    <customValue>
        <fullName>Foods India</fullName>
    </customValue>
    <customValue>
        <fullName>Malt</fullName>
    </customValue>
    <customValue>
        <fullName>CDT</fullName>
    </customValue>
    <customValue>
        <fullName>Foods Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA</fullName>
    </customValue>
    <customValue>
        <fullName>CE NA SS</fullName>
    </customValue>
    <description>Acronym or Abbreviation of Business Name</description>
    <masterLabel>Cargill Business Alias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SyncAccountTeamMemberHelper_Test.cls
/**
 Test Class to cover functionality of class:SyncAccountTeamMemberHelper
 */
@isTest
private class SyncAccountTeamMemberHelper_Test {
	
	public static AccountView__c accView;
	public static Account acc;
	public static Business__c BUnit;
	public static BusinessDetail__c BDetails;
	//create test data
	public static void createTestData()
	{
		//insert test data
        Map<String,Schema.RecordTypeInfo> recordTypeMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        acc = new Account();
        acc.Name = 'Test';
        acc.BillingCity = 'Test';
        acc.BillingState = 'Iowa';
        acc.BillingStreet = 'Test';
        acc.BillingPostalCode = 'Test';
        acc.ShippingCity = 'Test';
        acc.ShippingState = 'Iowa';
        acc.ShippingStreet = 'Test';
        acc.ShippingPostalCode = 'Test';
        acc.RecordTypeId= recordTypeMap.get('Global Account').getRecordTypeId();
        acc.Market_Channel__c='Retail Channel';
        insert(acc);
        acc.ShippingStreet = 'TestShippingStreet';
        
        Opportunity opp = new Opportunity();
        opp.Name='Test'; 
        opp.NextStep='test';                                   
        opp.CloseDate = System.today();                                    
        opp.AccountId=acc.id; 
        opp.StageName='Closed Won - One Time'; 
        opp.Probability=100;
        insert(opp);
        
        BUnit = new Business__c();
        BUnit.Name = 'Teat';
        BUnit.BusinessUnitAlias__c = 'GTM Corp Accts';
        BUnit.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        BUnit.CargillGroup__c = 'GoToMarket (GTM)';
        insert(BUnit);
        
        BDetails = new BusinessDetail__c();
        BDetails.Account__c = acc.Id;
        BDetails.BusinessUnit__c = BUnit.Id;
        BDetails.Status__c = 'Active';
        insert(BDetails);
        
        accView = new AccountView__c();
        accView.Account__c = acc.id;
        accView.Business__c = BUnit.id;
        accView.Business_Detail__c = BDetails.id;
        accView.User__c = UserInfo.getUserId();
        accView.Account_Access__c = 'Read/Write';
        accView.Account_Team_Role__c = 'Account Manager';
        accView.Case_Access__c = 'Read/Write';
        accView.Opportunity_Access__c = 'Read/Write';
        
        
	}
	
	
    static testMethod void insertAccountTeamMemberTest() {
        createTestData();
        Test.StartTest();
        
        //cover before insert functionality
        insert accView;
        
        system.assertEquals(accView.User__c,UserInfo.getUserId());
        //test delete functionality
       // delete accView;
        
        Test.StopTest();
        
    }
    
    
    static testMethod void insertAccountExtTeamMemberTest() {
        createTestData();
        
        
        AccountTeamMember accNewCr = new AccountTeamMember();
        accNewCr.UserId = UserInfo.getUserId();
        accNewCr.AccountId = acc.id;
        //accNewCr.AccountAccessLevel = 'Read/Write';
        //accNewCr.CaseAccessLevel= 'Read/Write';
        //accNewCr.OpportunityAccessLevel = 'Read/Write';
        accNewCr.TeamMemberRole = 'Account Manager';
        insert accNewCr;
        
        AccountView__c accView2 = new AccountView__c();
        accView2.Account__c = acc.id;
        accView2.Business__c = BUnit.id;
        accView2.Business_Detail__c = BDetails.id;
        accView2.User__c = UserInfo.getUserId();
        accView2.Account_Access__c = 'Read/Write';
        accView2.Account_Team_Role__c = 'Account Manager';
        accView2.Case_Access__c = 'Read/Write';
        accView2.Opportunity_Access__c = 'Read/Write';
        
        Test.StartTest();
        
        //cover before insert functionality
        insert accView2;
        
        system.assertEquals(accView.User__c,UserInfo.getUserId());
        
        List<AccountView__c> acList2 = new List<AccountView__c>();
        acList2.add(accView2);
        //test delete functionality
  		SyncAccountTeamMemberHelper syncAcc = new SyncAccountTeamMemberHelper(null,null,acList2);
    	syncAcc.deleteAccRec();
        
        Test.StopTest();
        
    }
    
    static testMethod void updateAccountTeamMemberTest() {
    	 createTestData();
    	 insert accView;
    	 
    	 Test.StartTest();
    	 //test before update functionality
	        accView.Opportunity_Access__c = 'Read Only';
	        update accView;
	        
	        system.assertNotEquals(accView.User__c,null);
	        List<AccountView__c> acList = new List<AccountView__c>();
	        acList.add(accView);
	        SyncAccountTeamMemberHelper syncAcc = new SyncAccountTeamMemberHelper(null,acList,null);
        	syncAcc.syncAccTeamupdate();
        	
        Test.StopTest();
    }
    
    static testMethod void updateAccountExtTeamMemberTest() {
    	 createTestData();
    	 insert accView;
    	 
    	 AccountTeamMember accNewCr = new AccountTeamMember();
        accNewCr.UserId = UserInfo.getUserId();
        accNewCr.AccountId = acc.id;
        //accNewCr.AccountAccessLevel = 'Read/Write';
        //accNewCr.CaseAccessLevel= 'Read/Write';
        //accNewCr.OpportunityAccessLevel = 'Read/Write';
        accNewCr.TeamMemberRole = 'Account Manager';
        insert accNewCr;
        
        AccountView__c accView2 = new AccountView__c();
        accView2.Account__c = acc.id;
        accView2.Business__c = BUnit.id;
        accView2.Business_Detail__c = BDetails.id;
        accView2.User__c = UserInfo.getUserId();
        accView2.Account_Access__c = 'Read/Write';
        accView2.Account_Team_Role__c = 'Account Manager';
        accView2.Case_Access__c = 'Read/Write';
        accView2.Opportunity_Access__c = 'Read/Write';
    	insert accView2; 
    	 Test.StartTest();
    	 //test before update functionality
	        accView.Opportunity_Access__c = 'Read Only';
	        update accView2;
	        
	        system.assertNotEquals(accView.User__c,null);
	        List<AccountView__c> acList = new List<AccountView__c>();
	        acList.add(accView2);
	        SyncAccountTeamMemberHelper syncAcc = new SyncAccountTeamMemberHelper(null,acList,null);
        	syncAcc.syncAccTeamupdate();
        	
        Test.StopTest();
    }
    
}