force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Profiles</relationshipLabel>
    <relationshipName>Customer_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Strategic Objective - Commercial Account</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPG_ParentAccountForStrategicObjective.cls
/**
@Author Vaishali
@name CPG_ParentAccountForStrategicObjective 
@CreateDate Sept 12, 2017
@Description Helper class for ParentAccountForStrategicObjective -process builder
@Version <1.0>
@reference Process Builder -ParentAccountForStrategicObjective
*/
Public class CPG_ParentAccountForStrategicObjective {

      @InvocableMethod(label='ParentAccount StrategicObjective' description='Customer Profile relationship for child account StrategicObjective')
      public static List<ID> setParentAcc(List<ID> CustProfIds) {  
          Set<ID> custID=new set<Id>();
          custID.addAll(CustProfIds);
          Map <ID,CustomerProfile__c> mapCustProf=new Map <ID,CustomerProfile__c>([SELECT Account__c,Account__r.ID,Account__r.ParentId FROM CustomerProfile__c where ID IN:custID]);
          List<StrategicObjective__c> lstStrObj=[SELECT Account__c,CustomerProfile__c FROM StrategicObjective__c where CustomerProfile__c IN:custID];
          List<StrategicObjective__c> newlstSB=new List<StrategicObjective__c>();
          For(StrategicObjective__c sb:lstStrObj){
              if(mapCustProf.Containskey(sb.CustomerProfile__c)){
                  CustomerProfile__c custPro=mapCustProf.get(sb.CustomerProfile__c);
                  sb.Account__c=custPro.Account__r.ParentId;
                  newlstSB.add(sb);
              }
          }
          database.update(newlstSB, false);
          return null;
      }
 }