force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Market_Channel__c.field-meta.xml
<CustomField>
    <fullName>Market_Channel__c</fullName>
    <formula>Text(Account__r.Market_Channel__c)</formula>
    <label>Market Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  StartDate__c &gt; TODAY(),
       &quot;Pending&quot;,
       IF(OR(EndDate__c &gt; TODAY(), ISNULL(EndDate__c),ISBLANK(EndDate__c)),
       &quot;Active&quot;,
       &quot;Expired&quot;
  ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPG_ParentAccountForStrategicObj_Test.cls
/****************************************
Name-CPG_ParentAccountForStrategicObj_Test
Created Date- 15/9/2017
Description-this is test class test functionolity of class CPG_ParentAccountForStrategicObjective used by process builder
******************************************/


@isTest
public class CPG_ParentAccountForStrategicObj_Test
{
    public static testMethod void setParentAcctest()
    {
        Account acc=new account(Name='testAcc',Market_Channel__c='Internal',Status__c='Active');
        insert acc;
        Account ChildAcc=new Account(Name='testCAcc',Market_Channel__c='Internal',Status__c='Active',ParentId=acc.Id);  
        insert ChildAcc;
        list<account> acclist=new list<account>{acc,ChildAcc};
        list<CustomerProfile__c> cplist1=CPG_TestFactory_Util.createTestCustomerProfiles(1,acclist);
        System.assertEquals(2, cplist1.size());
      
        list<CustomerProfile__c> cplist2=new list<CustomerProfile__c>{cplist1[0]};
        
        list<StrategicObjective__c> solist=CPG_TestFactory_Util.createTestStrategicObjectives(3,cplist2);
        solist[2].Name='TestSO';
        update solist[2];
        Delete solist[1];
        
        list<Id> cplist=new list<Id>{cplist1[0].Id,cplist1[1].Id};
        
        test.startTest();
        CPG_ParentAccountForStrategicObjective.setParentAcc(cplist);       
        test.stopTest();
    }
}