force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Express_Value__c.field-meta.xml
<CustomField>
    <fullName>Express_Value__c</fullName>
    <description>Express Value</description>
    <inlineHelpText>The values the customer states and try’s to align their products and services to such as Healthy food, Leader in Innovation,
 Best in class style.</inlineHelpText>
    <label>Express Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/fields/Strategic_Initiative__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Initiative__c</fullName>
    <description>Strategic Initiative</description>
    <inlineHelpText>Customers stated key drivers for the fiscal year. These are usually high level and apply across the business. 
 Examples would be Grow Food service market space by 5 points, Reduce procurement costs by 10%.</inlineHelpText>
    <label>Strategic Initiative</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  StartDate__c &gt; TODAY(),
       &quot;Pending&quot;,
       IF(OR(EndDate__c &gt; TODAY(), ISNULL(EndDate__c),ISBLANK(EndDate__c)),
       &quot;Active&quot;,
       &quot;Expired&quot;
  ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPG_CustomerProfileTrigger_Test.cls
/**
@Author: Cognizant
@name CPG_CustomerProfileTrigger_Test
@CreateDate Jan 10, 2018
@Description test class for CustomerProfileTrigger
*/ 
@isTest
public class CPG_CustomerProfileTrigger_Test 
{
    public static testMethod void testCustomerProfileStatus()
    {        
        
        //create account       
        list<Account> acclist=CPG_TestFactory_Util.createTestAccounts(2);
        acclist[0].Parentid=acclist[1].id;
        update acclist[0];
           
        //Create Customer Profile    
        list<CustomerProfile__c> lstCP = CPG_TestFactory_Util.createTestCustomerProfiles(1,acclist);
        
        test.startTest();
        lstCP[0].Name='Test CP2';
        update lstCP;
        list<CustomerProfile__c> lstCPDB =[select status__C from CustomerProfile__c where id=:lstCP[0].id];
        system.assertEquals('Not Started',lstCPDB[0].status__c,'Customer Profile Status not updated to In Progress.');
        //Create Strategic Objectives
        list<StrategicObjective__c> lstStratObj = CPG_TestFactory_Util.createTestStrategicObjectives(1,lstCP); 
        lstCP[0].Express_Value__c = 'Test CP Express Value string';
        lstCP[0].Strategic_Initiative__c = 'Test CP Strat Init string';
        update lstCP;
        list<CustomerProfile__c> lstCPDB01 =[select status__C from CustomerProfile__c where id=:lstCP[0].id];
        system.assertEquals('Complete',lstCPDB01[0].status__c,'Customer Profile Status not updated to In Progress.');
        
        //Test CP deletion flow
        delete lstCP;
        list<Account> lstAcc = new list<Account>();
        lstAcc = [select Has_Customer_Profile_at_Commercial_Level__c from Account where id=:acclist[0].id];
        system.assert(!lstAcc[0].Has_Customer_Profile_at_Commercial_Level__c,'Parent CP roll up not correct!');
        test.stopTest();            
    }
}