force-app/main/default/objects/Account_Plan_Opportunity__c/Account_Plan_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Account Plan Opportunity</label>
    <nameField>
        <displayFormat>APO-{0000}</displayFormat>
        <label>Account Plan Opportunitiy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan_Opportunity__c/fields/Account_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Detail__c</fullName>
    <label>Account Plan Detail</label>
    <referenceTo>AccountPlanDetail__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Account_Plan_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/AccountPlan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Account,Commercial Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlan__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <description>Link to Quip Account Plan Document</description>
    <label>Account Plan</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/AccountPlanDetail__c.object-meta.xml
<CustomObject>
    <label>Account Plan Detail</label>
    <nameField>
        <displayFormat>APD{000000}</displayFormat>
        <label>Account Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPlanDetail__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountPlanDetail__c/fields/Strategic_Objective__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Objective</label>
    <referenceTo>StrategicObjective__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Account_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerProfile__c/CustomerProfile__c.object-meta.xml
<CustomObject>
    <label>Customer Profile</label>
    <nameField>
        <label>Customer Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Profiles</relationshipLabel>
    <relationshipName>Customer_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Strategic_Objective_APD__c/Strategic_Objective_APD__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective-APD</label>
    <nameField>
        <displayFormat>APD-{0000}</displayFormat>
        <label>Strategic Objective APD Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Objective-APDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Objective_APD__c/fields/Account_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Detail__c</fullName>
    <label>Account Plan Detail</label>
    <referenceTo>AccountPlanDetail__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objective_APDs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Objective_APD__c/fields/Strategic_Objective__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Objective__c</fullName>
    <label>Strategic Objective</label>
    <referenceTo>StrategicObjective__c</referenceTo>
    <relationshipLabel>Account Plan Details</relationshipLabel>
    <relationshipName>Strategic_Objective_APDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/StrategicObjective__c.object-meta.xml
<CustomObject>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StrategicObjective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Strategic Objective - Commercial Account</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>AccountPlan__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/CustomerProfile__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfile__c</fullName>
    <label>Customer Profile</label>
    <referenceTo>CustomerProfile__c</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StrategicObjective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Strategic Objectives</relationshipLabel>
    <relationshipName>Strategic_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CPG_AddAccountPlanDetailController.cls
/**
Class Name: CPG_AddAccountPlanDetailController
Created Date: Oct-15-2017
Created By: Cognizant
This class is  controller class for component used for adding multiple Account Plan Details.
**/
public class CPG_AddAccountPlanDetailController{
public static list<id> lstStratIds= new list<id>();
public static id APDid;
@AuraEnabled
public static List<StrategicObjective__c> getStratObjectives(string accountplanid) {
    string accountid;
    list<AccountPlan__c> lstACP = [select account__c from accountplan__c where id=:accountplanid];
    if(!lstACP.isEmpty()){
       accountid= lstACP[0].account__c;
    }
    list<StrategicObjective__c> lstStrtObj = new list<StrategicObjective__c>();
    lstStrtObj  = [select Id, Name,  EndDate__c from StrategicObjective__c where CustomerProfile__r.account__c=:accountid or CustomerProfile__r.account__r.parentId=:accountid or CustomerProfile__r.account__r.parent.parentid=:accountid];
    return lstStrtObj ;
}
@AuraEnabled
public static List<Opportunity> addAPobjectives(list<id> StratIds, string accountplanid){
    string accountid;
    lstStratIds.addAll(StratIds);
    list<AccountPlan__c> lstACP = [select account__c from accountplan__c where id=:accountplanid];
    if(!lstACP.isEmpty()){
       accountid= lstACP[0].account__c;
    }
    lstStratIds = new list<id>();
    lstStratIds.addAll(StratIds);
    //Insert Account Plan Detail
    if(!StratIds.isEmpty()){
        AccountPlanDetail__c apd= new AccountPlanDetail__c(Account_Plan__c=accountplanid);
        insert apd;
        APDid = apd.id;
        //Insert Account Plan Detail Objective
        list<Strategic_Objective_APD__c> lstAPDObj = new list<Strategic_Objective_APD__c>();
        
        for(id idObj:StratIds){
            if(idObj!=null){
            lstAPDObj.add(new Strategic_Objective_APD__c(Strategic_Objective__c = idObj, Account_Plan_Detail__c = APDid, External_ID__c= idObj+'|'+APDid));
            }
        }
        if(!lstAPDObj.isEmpty()){
            upsert lstAPDObj external_Id__c;
        }
    
    }
    list<Opportunity> lstOpp = new list<Opportunity>();
    lstOpp = [select Id, Name, Account.Name, CloseDate from Opportunity where accountid=:accountid or  account.parentId=:accountid or  account.parent.parentid=:accountid];
    return lstOpp;
}

@AuraEnabled
public static void saveAP(list<id> OppIds, string accountplanid, list<id> StratIds) {
    //Insert Account Plan Detail Opportunities
    list<Account_Plan_Opportunity__c> lstAPDOpp = new list<Account_Plan_Opportunity__c>();
    string iAPD = [select id from AccountPlanDetail__c where Account_Plan__c=:accountplanid and createdbyid=:userInfo.getUserId() order by createddate desc limit 1].id;
    for(id idOpp :OppIds){
        if(idOpp!=null){
            lstAPDOpp.add(new Account_Plan_Opportunity__c(opportunity__c= idOpp, Account_Plan_Detail__c = iAPD));
        }
    }
    if(!lstAPDOpp.isEmpty()){
        insert lstAPDOpp;
    }
}

}