force-app/main/default/objects/CPQCollectionMap__c/CPQCollectionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CPQ Collection Map</label>
</CustomObject>

force-app/main/default/objects/CPQCollectionMap__c/fields/CPQCollection__c.field-meta.xml
<CustomField>
    <fullName>CPQCollection__c</fullName>
    <label>CPQCollection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/LEGACY_BUSINESS__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_BUSINESS__c</fullName>
    <label>LEGACY BUSINESS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_1__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_1__c</fullName>
    <label>PRODUCT HIER 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_2__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_2__c</fullName>
    <label>PRODUCT HIER 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_3__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_3__c</fullName>
    <label>PRODUCT HIER 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_4__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_4__c</fullName>
    <label>PRODUCT HIER 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_5__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_5__c</fullName>
    <label>PRODUCT HIER 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPG_ProductTriggerHelper.cls
/**
@Author - Cognizant
@name - CPG_ProductTriggerHelper
@CreateDate - Jan-19-2018
@Description - This Trigger Helper class executes trigger logic for Products.
@Revision-
*/ 
//Using without Sharing Class in order to get Product fields which are not exposed to non-admin users
public without Sharing class CPG_ProductTriggerHelper{
//Method to update Product Collection for updated Products
public static void updateProductCollection(map<id,Product2> mapProductsOld , list<Product2> lstProductsNew){
    if(lstProductsNew!=null){
        //Get all Collection settings
        list<CPQCollectionMap__c> lstProdCollection = CPQCollectionMap__c.getAll().values();
        //Loop through eligible Products to match Collection
        for(Product2 prod:lstProductsNew){
            
        if(mapProductsOld==null || (prod.PRODUCT_HIER_1__c!= mapProductsOld.get(prod.id).PRODUCT_HIER_1__c || prod.legacy_business__c!= mapProductsOld.get(prod.id).legacy_business__c || prod.PRODUCT_HIER_2__c!= mapProductsOld.get(prod.id).PRODUCT_HIER_2__c || prod.PRODUCT_HIER_3__c!= mapProductsOld.get(prod.id).PRODUCT_HIER_3__c || prod.PRODUCT_HIER_4__c!= mapProductsOld.get(prod.id).PRODUCT_HIER_4__c || prod.PRODUCT_HIER_5__c!= mapProductsOld.get(prod.id).PRODUCT_HIER_5__c)){
                for(CPQCollectionMap__c coll:lstProdCollection){
                    //Not using Custom setting map due to negation logic constraint
                    if(prod.legacy_business__c==coll.legacy_business__c && (coll.PRODUCT_HIER_1__c ==null || (coll.PRODUCT_HIER_1__c == prod.PRODUCT_HIER_1__c ))  && (coll.PRODUCT_HIER_2__c ==null || (coll.PRODUCT_HIER_2__c == prod.PRODUCT_HIER_2__c )) && (coll.PRODUCT_HIER_4__c ==null || (coll.PRODUCT_HIER_4__c == prod.PRODUCT_HIER_4__c ))  && (coll.PRODUCT_HIER_5__c ==null || (coll.PRODUCT_HIER_5__c == prod.PRODUCT_HIER_5__c ))){
                        if(coll.PRODUCT_HIER_3__c ==null || (coll.PRODUCT_HIER_3__c == prod.PRODUCT_HIER_3__c || (coll.PRODUCT_HIER_3__c.contains('(') && (prod.PRODUCT_HIER_3_Neg__c==null || !coll.PRODUCT_HIER_3__c.contains(prod.PRODUCT_HIER_3_Neg__c))))){
                            prod.CPQCollection__c = coll.CPQCollection__c;
                            break;
                        }
                    }
                }
            }
        }
    }
}

}