force-app/main/default/objects/CPQCollectionMap__c/CPQCollectionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CPQ Collection Map</label>
</CustomObject>

force-app/main/default/objects/CPQCollectionMap__c/fields/CPQCollection__c.field-meta.xml
<CustomField>
    <fullName>CPQCollection__c</fullName>
    <label>CPQCollection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/LEGACY_BUSINESS__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_BUSINESS__c</fullName>
    <label>LEGACY BUSINESS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_1__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_1__c</fullName>
    <label>PRODUCT HIER 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_2__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_2__c</fullName>
    <label>PRODUCT HIER 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_3__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_3__c</fullName>
    <label>PRODUCT HIER 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_4__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_4__c</fullName>
    <label>PRODUCT HIER 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQCollectionMap__c/fields/PRODUCT_HIER_5__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_HIER_5__c</fullName>
    <label>PRODUCT HIER 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/batchPRODUCT_CPQCollectionUpdate.cls
/**
Class Name: batchPRODUCT_CPQCollectionUpdate 
Description: This batch class is used for updating CPQ Collection value
CreatedDate: 08-28-2018
**/
global class batchPRODUCT_CPQCollectionUpdate implements Database.Batchable<sObject>,Database.Stateful {
    private static string query ='select id,legacy_business__c,PRODUCT_HIER_1__c,PRODUCT_HIER_2__c,PRODUCT_HIER_3__c,PRODUCT_HIER_3_DESC__c,PRODUCT_HIER_4__c,PRODUCT_HIER_5__c,CPQCollection__c,PRODUCT_HIER_3_Neg__c from product2';
    public list<CPQCollectionMap__c> lstProdCollection = CPQCollectionMap__c.getAll().values();
    global Database.QueryLocator start(Database.BatchableContext bc) {
      return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<product2> lstProductsNew){
        map<string, map<string,string>> mapAccTeamAccess = new map<string, map<string,string>>();
        List<product2> prdLst = new List<product2>();
        for(Product2 prod: lstProductsNew){
            
        for(CPQCollectionMap__c coll:lstProdCollection){
                    //Not using Custom setting map due to negation logic constraint
                    if(prod.legacy_business__c==coll.legacy_business__c && (coll.PRODUCT_HIER_1__c ==null || (coll.PRODUCT_HIER_1__c == prod.PRODUCT_HIER_1__c ))  && (coll.PRODUCT_HIER_2__c ==null || (coll.PRODUCT_HIER_2__c == prod.PRODUCT_HIER_2__c )) && (coll.PRODUCT_HIER_4__c ==null || (coll.PRODUCT_HIER_4__c == prod.PRODUCT_HIER_4__c ))  && (coll.PRODUCT_HIER_5__c ==null || (coll.PRODUCT_HIER_5__c == prod.PRODUCT_HIER_5__c ))){
                        if(coll.PRODUCT_HIER_3__c ==null || (coll.PRODUCT_HIER_3__c == prod.PRODUCT_HIER_3_Desc__c || (coll.PRODUCT_HIER_3__c.contains('(') && (prod.PRODUCT_HIER_3_Neg__c==null || !coll.PRODUCT_HIER_3__c.contains(prod.PRODUCT_HIER_3_Neg__c))))){
                            prod.CPQCollection__c = coll.CPQCollection__c;
                            prdLst.add(prod);
                            break;
                        }
                    }
           }
  
        }
        Database.update(prdLst);
        
    }    

    global void finish(Database.BatchableContext bc){
            
    }  
   
}