force-app/main/default/objects/Knowledge__kav/fields/CS_Category__c.field-meta.xml
<CustomField>
    <fullName>CS_Category__c</fullName>
    <description>This field will define the category of the knowledge article.</description>
    <inlineHelpText>Select Knowledge Category</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Information</fullName>
            </value>
            <value>
                <fullName>Job Aid</fullName>
            </value>
            <value>
                <fullName>Leadership Presentations</fullName>
            </value>
            <value>
                <fullName>On Boarding Documents</fullName>
            </value>
            <value>
                <fullName>System Documentation</fullName>
            </value>
            <value>
                <fullName>Fresh Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CS_Market_Channel__c.field-meta.xml
<CustomField>
    <fullName>CS_Market_Channel__c</fullName>
    <description>This field will define the market channel that article belongs to. There will be 4 options available Food Service, Protein Ingredients, Retail &amp; General.</description>
    <inlineHelpText>Market Channel of Knowledge Article</inlineHelpText>
    <label>Market Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Protein Ingredients</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CS_OverrideCntrl.cls
/*
*Author: Vasanthi Narayan
*Project: Protein Service Cloud Implementation
*This Class have the methods called from the components : CS_Knowledge_banner, CS_ServiceComplaint_New_Override, CS_KnowledgePublish_Override
*/

public class CS_OverrideCntrl {
    /*
     *Author: Vasanthi Narayan
     *Description: Method to get the Case Reason from the Case Id passed
     *
     */
    @auraEnabled
    public static String getcaseReason(String caseId){
        String csReason;
        case cs ;
        if(caseId != null){
            
            cs =[Select id, Reason from case where id =: caseId];
        }
        csReason= cs.Reason;
       return csReason;
        
    }
    
     /*
     *Author: Vasanthi Narayan
     *Description: Method to get the knowledge Record and locked status from the Knowledge Id passed
     *
     */
    @auraEnabled
    public static Map<Boolean,Knowledge__kav> getknowledgeRec(String knowledgeId){
        Map<Boolean,Knowledge__kav> returnValue = new Map<Boolean,Knowledge__kav>();
        Knowledge__kav  knldge;
         Boolean isLockedRecord = false;
        if(knowledgeId != null){
            
            knldge = [select id,KnowledgeArticleId,  CS_Category__c, PublishStatus, CS_Market_Channel__c from Knowledge__kav where id =: knowledgeId];
             isLockedRecord = Approval.isLocked(knldge.id);
            returnValue.put(isLockedRecord,knldge);
        }
      
        return returnValue;
        
    }
    
     /*
     *Author: Vasanthi Narayan
     *Description: Method to get the knowledge Record from the Knowledge Id passed
     *
     */
    @auraEnabled
    public static Knowledge__kav getknowledgeRecs(String knowledgeId){
       
        Knowledge__kav  knldge;
        
        if(knowledgeId != null){
            
            knldge = [select id,KnowledgeArticleId,  CS_Category__c, PublishStatus, CS_Market_Channel__c from Knowledge__kav where id =: knowledgeId];
        
        }
       
        return knldge;
        
    }
    
    /*
     *Author: Vasanthi Narayan
     *Description: Method to publish the knowledge Record as New
     *
     */
    @auraEnabled
    public static boolean publishArticle(String knowledgeId){
        
        KbManagement.PublishingService.publishArticle(knowledgeId, true);
        return true;
    }
    
}