force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_profile__c/Integration_profile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All list of Profiles for OOTB config &amp; customization</description>
    <label>Integration profile</label>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlan__c/TelesalesPlan__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlan__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>Out of Office</fullName>
            </value>
            <value>
                <fullName>Sick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TelesalesPlan__c/recordTypes/ContingencyPlan.recordType-meta.xml
<RecordType>
    <fullName>ContingencyPlan</fullName>
    <active>true</active>
    <label>Contingency Plan</label>
</RecordType>

force-app/main/default/objects/TelesalesPlanDetail__c/TelesalesPlanDetail__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan Detail</label>
    <nameField>
        <displayFormat>TPD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hour</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipName>TelesalesPlanDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/TelesalesPlan__c.field-meta.xml
<CustomField>
    <fullName>TelesalesPlan__c</fullName>
    <label>TelesalesPlan</label>
    <referenceTo>TelesalesPlan__c</referenceTo>
    <relationshipName>TelesalesPlanDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AVX_TelesalesPlanDetailTriggerHelper_tst.cls
@isTest
public class AVX_TelesalesPlanDetailTriggerHelper_tst {
    @TestSetup
    static void makeData(){
        User objSupervisorUser = AVX_DataGenerator_cls.createUser('Supervisor');
        insert objSupervisorUser;

        User objTelemarketerUser = AVX_DataGenerator_cls.createUser('Telemarketer');
        insert objTelemarketerUser;

        Integration_profile__c objCustomSettings = AVX_DataGenerator_cls.createCustomSettings(true);
        insert objCustomSettings;

        Account objGlobalAcc = AVX_DataGenerator_cls.createGlobalAccount('GlobalAcc');
        insert objGlobalAcc;

        Account objCommercialAcc = AVX_DataGenerator_cls.createCommercialAccount('CommercialAcc', objGlobalAcc);
        insert objCommercialAcc;

        Account objPayerAcc = AVX_DataGenerator_cls.createPayerAccount('PayerAcc', objCommercialAcc);
        insert objPayerAcc;

        Bill_To__c objBillTo = AVX_DataGenerator_cls.createBillTo('BillTo1', objPayerAcc, objCommercialAcc);
        insert objBillTo;

        Ship_To__c objShipTo = AVX_DataGenerator_cls.createShipTo('ShipTo1', objPayerAcc, objBillTo);
        insert objShipTo;

        TelesalesPlan__c objTeleSalesPlan = AVX_DataGenerator_cls.createTeleSalesPlan(objTelemarketerUser, objSupervisorUser);
        insert objTeleSalesPlan;     

        TelesalesPlanDetail__c objTeleSalesPlanDetail = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        insert objTeleSalesPlanDetail;

        TelesalesPlan__c objContingencyPlan = AVX_DataGenerator_cls.createContingencyPlan(objTeleSalesPlan);
        insert objContingencyPlan;

        TelesalesPlanDetail__c objTeleSalesPlanDetail2 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objContingencyPlan, objCommercialAcc, objShipTo);
        insert objTeleSalesPlanDetail2;
    }

    @isTest 
    static void testTaskCreation(){
        User user = [SELECT Id FROM User WHERE FirstName = 'Supervisor'];
        System.assert(user != null);

        TelesalesPlanDetail__c objTeleSalesPlanDetail = [SELECT Id, Hours__c FROM TelesalesPlanDetail__c WHERE Ship_To__r.Name = 'ShipTo1' LIMIT 1];
        System.assert(objTeleSalesPlanDetail != null);

        Task objTask = [SELECT Id, Status FROM Task WHERE TelesalesPlanDetail__c = :objTeleSalesPlanDetail.Id LIMIT 1];
        System.assert(objTask != null);

        TelesalesPlan__c objTelesalesPlan = [SELECT Id FROM TelesalesPlan__c WHERE Reason__c = 'Holidays' LIMIT 1];
        System.assert(objTelesalesPlan != null);

        TelesalesPlanDetail__c objTeleSalesPlanDetail2 = [SELECT Id FROM TelesalesPlanDetail__c WHERE TelesalesPlan__r.RecordType.DeveloperName = 'ContingencyPlan'];
        System.assert(objTeleSalesPlanDetail2 != null);

        Test.startTest();
        System.runAs(user){
            AVX_TelesalesPlanDetailTriggerHelper_cls newHelper = new AVX_TelesalesPlanDetailTriggerHelper_cls();
            objTeleSalesPlanDetail.Hours__c += 50000;
            update objTeleSalesPlanDetail;

            objTask.Status = 'InProgress';
            update objTask;

            objTeleSalesPlanDetail.Hours__c += 100000;
            update objTeleSalesPlanDetail;

            delete objTeleSalesPlanDetail;

            List<Task> lstTask = [SELECT Id FROM Task WHERE TelesalesPlanDetail__c = :objTeleSalesPlanDetail.Id];
            System.assert(lstTask.isEmpty());
        }
        Test.stopTest();

    }
}