force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_profile__c/Integration_profile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All list of Profiles for OOTB config &amp; customization</description>
    <label>Integration profile</label>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TelesalesPlan__c/TelesalesPlan__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TelesalesPlanDetail__c/TelesalesPlanDetail__c.object-meta.xml
<CustomObject>
    <label>Telesales Plan Detail</label>
    <nameField>
        <displayFormat>TPD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telesales Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/DayOfTheWeek__c.field-meta.xml
<CustomField>
    <fullName>DayOfTheWeek__c</fullName>
    <label>Day Of The Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monday</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Tuesday</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Wednesday</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Thursday</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Friday</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Saturday</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Sunday</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipName>TelesalesPlanDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TelesalesPlanDetail__c/fields/TelesalesPlan__c.field-meta.xml
<CustomField>
    <fullName>TelesalesPlan__c</fullName>
    <label>TelesalesPlan</label>
    <referenceTo>TelesalesPlan__c</referenceTo>
    <relationshipName>TelesalesPlanDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AVX_CreateTasksByPlan_tst.cls
@isTest 
public with sharing class AVX_CreateTasksByPlan_tst {
    @TestSetup
    static void makeData(){
        User objSupervisorUser = AVX_DataGenerator_cls.createUser('Supervisor');
        insert objSupervisorUser;

        User objTelemarketerUser = AVX_DataGenerator_cls.createUser('Telemarketer');
        insert objTelemarketerUser;

        Integration_profile__c objCustomSettings = AVX_DataGenerator_cls.createCustomSettings(true);
        insert objCustomSettings;

        Account objGlobalAcc = AVX_DataGenerator_cls.createGlobalAccount('GlobalAcc');
        insert objGlobalAcc;

        Account objCommercialAcc = AVX_DataGenerator_cls.createCommercialAccount('CommercialAcc', objGlobalAcc);
        insert objCommercialAcc;

        Account objPayerAcc = AVX_DataGenerator_cls.createPayerAccount('PayerAcc', objCommercialAcc);
        insert objPayerAcc;

        Bill_To__c objBillTo = AVX_DataGenerator_cls.createBillTo('BillTo1', objPayerAcc, objCommercialAcc);
        insert objBillTo;

        Ship_To__c objShipTo = AVX_DataGenerator_cls.createShipTo('ShipTo1', objPayerAcc, objBillTo);
        objShipTo.Commercial_Account__c = objCommercialAcc.Id;
        insert objShipTo;
        
        TelesalesPlan__c objTeleSalesPlan = AVX_DataGenerator_cls.createTeleSalesPlan(objTelemarketerUser, objSupervisorUser);
        objTeleSalesPlan.StartDate__c = Date.today();
        objTeleSalesPlan.EndDate__c = Date.today();
        insert objTeleSalesPlan;

        TelesalesPlanDetail__c objTeleSalesPlanDetail = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail.DayOfTheWeek__c = '1';
        insert objTeleSalesPlanDetail;

        TelesalesPlanDetail__c objTeleSalesPlanDetail2 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail2.DayOfTheWeek__c = '2';
        insert objTeleSalesPlanDetail2;

        TelesalesPlanDetail__c objTeleSalesPlanDetail3 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail3.DayOfTheWeek__c = '3';
        insert objTeleSalesPlanDetail3;

        TelesalesPlanDetail__c objTeleSalesPlanDetail4 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail4.DayOfTheWeek__c = '4';
        insert objTeleSalesPlanDetail4;

        TelesalesPlanDetail__c objTeleSalesPlanDetail5 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail5.DayOfTheWeek__c = '5';
        insert objTeleSalesPlanDetail5;

        TelesalesPlanDetail__c objTeleSalesPlanDetail6 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail6.DayOfTheWeek__c = '6';
        insert objTeleSalesPlanDetail6;

        TelesalesPlanDetail__c objTeleSalesPlanDetail7 = AVX_DataGenerator_cls.createTeleSalesPlanDetail(objTeleSalesPlan, objCommercialAcc, objShipTo);
        objTeleSalesPlanDetail7.DayOfTheWeek__c = '7';
        insert objTeleSalesPlanDetail7;
    }

    @isTest
    static void createTaskbyPlanRun(){
        Test.startTest();
        AVX_CreateTasksByPlan_sch sch = new AVX_CreateTasksByPlan_sch();      
        String schTime = '0  00 1 3 * ?';
        system.schedule('Test', schTime, sch);
        Test.stopTest();


    }

    @isTest
    static void createTaskbyPlan(){
        Date dateParam = Date.newInstance(2020, 10, 03);

        Test.startTest();
        AVX_CreateTasksByPlan_batch bch0 = new AVX_CreateTasksByPlan_batch();

        TelesalesPlan__c objTeleSalesPlan = [SELECT Id, StartDate__c, EndDate__c FROM TelesalesPlan__c LIMIT 1 ];
        objTeleSalesPlan.StartDate__c = dateParam;
        objTeleSalesPlan.EndDate__c = dateParam;
        update objTeleSalesPlan;

        AVX_CreateTasksByPlan_batch bch = new AVX_CreateTasksByPlan_batch(dateParam);
        Database.executeBatch(bch);
        Test.stopTest();

        Task task1 = [SELECT ShipTo__c, TelesalesPlan__c, Subject, ShipTo__r.Commercial_Account__r.Name FROM task LIMIT 1 ];
        System.AssertEquals(task1.ShipTo__c, [SELECT Id FROM Ship_To__c LIMIT 1].Id);
        System.AssertEquals(task1.TelesalesPlan__c, [SELECT Id FROM TelesalesPlan__c LIMIT 1].Id);


    }













}