force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/CS_Ship_To_Contact_Relation__c.object-meta.xml
<CustomObject>
    <description>This is the junction object to relate contact to ship to. The relation between this object and contact &amp; Ship To is maintained as lookup relation so that the record in this object can be edited.</description>
    <label>Ship To Contact Relation</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Ship To Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship To Contact Relation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/fields/CS_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>CS_Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship To related to same commercial account as that of contact.</description>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Ship_To_Contact_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_profile__c/Integration_profile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All list of Profiles for OOTB config &amp; customization</description>
    <label>Integration profile</label>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AVX_ShipToContactRelationTgrHelper_tst.cls
@isTest
public class AVX_ShipToContactRelationTgrHelper_tst {
    @TestSetup
    static void makeData(){
        User objUser = AVX_DataGenerator_cls.createUser('Misa');
        insert objUser;

        Integration_profile__c objCustomSettings = AVX_DataGenerator_cls.createCustomSettings(true);
        insert objCustomSettings;

        Account objGlobalAcc = AVX_DataGenerator_cls.createGlobalAccount('Global Acc');
        insert objGlobalAcc;

        Account objCommercialAcc = AVX_DataGenerator_cls.createCommercialAccount('Commercial Acc', objGlobalAcc);
        insert objCommercialAcc;

        Account objPayerAcc = AVX_DataGenerator_cls.createPayerAccount('Payer Acc', objCommercialAcc);
        insert objPayerAcc;

        Contact objContact = AVX_DataGenerator_cls.createContact('El', objGlobalAcc, 'misa@el.com');
        insert objContact;

        Bill_To__c objBillTo = AVX_DataGenerator_cls.createBillTo('BillTo1', objPayerAcc, objCommercialAcc);
        insert objBillTo;

        Ship_To__c objShipTo = AVX_DataGenerator_cls.createShipTo('ShipTo1', objPayerAcc, objBillTo);
        insert objShipTo;   

        CS_Ship_To_Contact_Relation__c objShipToContact = AVX_DataGenerator_cls.createShipToContactRelation(objContact, objShipTo, false);
        insert objShipToContact;
    }        

    @isTest 
    static void relateContactPrimaryContactTest(){
        User objUser = [SELECT Id FROM User WHERE FirstName = 'Misa'];
        System.assert(objUser != null);

        Contact objContact = [SELECT Id FROM Contact WHERE LastName = 'El' LIMIT 1];
        System.assert(objContact != null);

        Ship_To__c objShipTo = [SELECT Id FROM Ship_To__c WHERE Name = 'ShipTo1' LIMIT 1];
        System.assert(objShipTo != null);

        CS_Ship_To_Contact_Relation__c objShipToContact = [SELECT Id, PrimaryContact__c FROM CS_Ship_To_Contact_Relation__c WHERE CS_Ship_To__r.Name = 'ShipTo1' LIMIT 1];
        System.assert(objShipToContact != null);

        Test.startTest();
        System.runAs(objUser){
            objShipToContact.PrimaryContact__c = true;
            update objShipToContact;
        }
        Test.stopTest();
    }
}