force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Default_Currency__c.field-meta.xml
<CustomField>
    <fullName>Default_Currency__c</fullName>
    <label>Default Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>MXP</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>HNL</fullName>
            </value>
            <value>
                <fullName>GTQ</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>NIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <label>ERP Number</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Global_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System__c</fullName>
    <label>Legacy System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XLGO</fullName>
            </value>
            <value>
                <fullName>XLDM</fullName>
            </value>
            <value>
                <fullName>CBS</fullName>
            </value>
            <value>
                <fullName>CTCM</fullName>
            </value>
            <value>
                <fullName>PROTEAN</fullName>
            </value>
            <value>
                <fullName>CVAP EGG</fullName>
            </value>
            <value>
                <fullName>FIVE STAR</fullName>
            </value>
            <value>
                <fullName>CFD</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>JDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_RecordType_System_Mapping__mdt/Opportunity_RecordType_System_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Opportunity RecordType System Mapping</label>
    <pluralLabel>Opportunity RecordType System Mapings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity_RecordType_System_Mapping__mdt/fields/Legacy_Systems__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Systems__c</fullName>
    <label>Legacy Systems</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Bill_To__c/Quote_Bill_To__c.object-meta.xml
<CustomObject>
    <label>Quote Bill To</label>
    <nameField>
        <displayFormat>QB-{00000}</displayFormat>
        <label>Quote Bill To Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Bill To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Bill_To__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Bill_To__c</referenceTo>
    <relationshipLabel>Quote Bill To</relationshipLabel>
    <relationshipName>Quote_Bill_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Bill_To__c/fields/PROS_Quote__c.field-meta.xml
<CustomField>
    <fullName>PROS_Quote__c</fullName>
    <label>PROS Quote</label>
    <referenceTo>CameleonCPQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Bill To</relationshipLabel>
    <relationshipName>Quote_Bill_To</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Sold_To__r.Default_Currency__c)</formula>
    <label>Default Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <label>ERP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Global_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System__c</fullName>
    <label>Legacy System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XLGO</fullName>
            </value>
            <value>
                <fullName>XLDM</fullName>
            </value>
            <value>
                <fullName>CBS</fullName>
            </value>
            <value>
                <fullName>CTCM</fullName>
            </value>
            <value>
                <fullName>PROTEAN</fullName>
            </value>
            <value>
                <fullName>FIVE STAR</fullName>
            </value>
            <value>
                <fullName>CFD</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>CVAP EGG</fullName>
            </value>
            <value>
                <fullName>JDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddBillTosToPROSQuoteExtension.cls
public  with sharing class AddBillTosToPROSQuoteExtension {
    private CameleonCPQ__Quote__c quote;
    public list<wrapBillTo> lstBillTos{get;set;}
    private string quoteCurrency;
    set<string> setQuoteBillTos = new set<string>();

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public AddBillTosToPROSQuoteExtension(ApexPages.StandardController stdController) {
        this.quote = (CameleonCPQ__Quote__c)stdController.getRecord();       
        CameleonCPQ__Quote__c prosQuote = [SELECT Id,Name,CameleonCPQ__AccountId__c,   OpportunityId__r.recordtype.developerName,Pricing_Type__c FROM CameleonCPQ__Quote__c WHERE Id=: this.quote.Id];
        
        Boolean displayBillTos=  false;
        if (prosQuote.Pricing_Type__c != null && prosQuote.Pricing_Type__c.equalsIgnoreCase('PPP')){
            displayBillTos = true;
        }
        
        Id accountId = prosQuote.CameleonCPQ__AccountId__c;
        string oppType = prosQuote.OpportunityId__r.recordtype.developerName;
        string oppSystems;
        if(oppType!=null){
            list<Opportunity_RecordType_System_Mapping__mdt> lstOppSystems = [select Legacy_Systems__c from Opportunity_RecordType_System_Mapping__mdt where DeveloperName=:oppType];    
            if(lstOppSystems!=null && lstOppSystems.size()>0){
                oppSystems = lstOppSystems[0].Legacy_Systems__c;
            }
        }
        for(Quote_Bill_To__c qbt:[select Bill_To__c, bill_to__r.Default_Currency__c from Quote_Bill_To__c where pros_quote__c=:this.quote.id]){
            if(quoteCurrency!=null && qbt.bill_to__r.Default_Currency__c!=null){
                quoteCurrency = qbt.bill_to__r.Default_Currency__c;
            } 
            setQuoteBillTos.add(qbt.Bill_To__c);   
        }
        
        if (accountId != null && displayBillTos)
        {
            //for(Ship_To__c st : [select Id, Name,Payer__c,description__c,currency__c,City__c,state__c, ERP_Number__c, Legacy_System__c,Commercial_Account__c from Ship_To__c where (Commercial_Account__c = :accountId OR Payer__r.Parentid=:accountId)  AND id not in :setQuoteBillTos AND Status__c = 'Active']) {
            //Pull list of all available Ship Tos
            Boolean alreadySelected = false;
            for(Bill_To__c bt : [select Id, Name,Payer__c,description__c,Default_Currency__c,City__c,state__c, ERP_Number__c, Legacy_System__c,Commercial_Account__c,Global_Account__c from Bill_To__c where (Commercial_Account__c = :accountId OR Payer__r.Parentid=:accountId OR Global_Account__c=: accountId)  AND Status__c = 'Active']) {
                if(lstBillTos==null){
                    lstBillTos= new list<wrapBillTo>();
                }
                //Check if current Ship-Tos already selected
               	alreadySelected = false;
                if (setQuoteBillTos.contains(bt.Id)){
                    alreadySelected =true;
                }
                if(oppSystems!=null && oppType!='Non_CPQ'){
                    if((bt.Legacy_System__c!= null)&& (oppSystems.toLowerCase().indexOf(bt.Legacy_System__c.toLowerCase() )>=0)){
                        lstBillTos.add(new wrapBillTo(bt,alreadySelected));
                    }
                }
                else{
                    lstBillTos.add(new wrapBillTo(bt,alreadySelected));
                }
                //lstBillTos.add(new wrapBillTo(st));
            }
        }
    }
    public pageReference backtoQuote(){
        PageReference pageRef = new PageReference('/'+this.quote.id  + '?core.apexpages.devmode.url=1' ); 
        pageRef.setRedirect(true); 
        return pageRef; 
    }
    public pageReference addBillTos(){
        //Delete all BillTo first
        SmartCPQUtils.removeAllBillTos(this.quote);
        //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value'));
        list<Quote_Bill_To__c> lstQuoteBillTo = new list<Quote_Bill_To__c>();   
        for(wrapBillTo bt:lstBillTos){
            if(bt.selected && (quoteCurrency==null || bt.BillTo.Default_Currency__c==quoteCurrency)){
                string externalId = this.quote.Id+'|'+ bt.BillTo.id;
                lstQuoteBillTo.add(new Quote_Bill_To__c(PROS_Quote__c=this.quote.Id, Bill_To__c = bt.BillTo.id, External_Id__c=externalId));    
                system.debug('selected ship:'+bt.BillTo.Name);
            }
            else if(bt.selected && quoteCurrency!=null && bt.BillTo.Default_Currency__c==quoteCurrency){
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: All selected Bill To\'s must have same currency!');
                ApexPages.addMessage(errMsg);  
                return null;       
            }
        }
        savePoint sp= database.setSavePoint();
        try{
            upsert lstQuoteBillTo;
        }catch(DmlException ex){
            ApexPages.addMessages(ex); 
            database.Rollback(sp);
            return null;   
        }
        PageReference pageRef = new PageReference('/'+this.quote.id  + '?core.apexpages.devmode.url=1'); 
        pageRef.setRedirect(true); 
        return pageRef; 
    }
    
    public pageReference addAllBillTos(){
        CameleonCPQ__Quote__c prosQuote = [SELECT Id,Name,CameleonCPQ__AccountId__c,OpportunityId__r.recordtype.developerName FROM CameleonCPQ__Quote__c WHERE Id=: this.quote.Id];

        SmartCPQUtils.addAllBillTos(prosQuote,null);
        return this.backToQuote();
    }
    
    public pageReference removeAllBillTos(){
        SmartCPQUtils.removeAllBillTos(quote);
        return this.backToQuote();
    }    
    
    public void selectAllBillTos(){
        for(wrapBillTo bh:lstBillTos){
            bh.setSelected(true);
        }
    }
    
    public void unSelectAllBillTos(){
        for(wrapBillTo bh:lstBillTos){
            bh.setSelected(false);
        }
    }
    
    public wrapBillTo createNewWrapBillTo(Bill_To__c billTo){
        wrapBillTo wbt = new  wrapBillTo(billTo,false);
        return wbt;
    }
    public class wrapBillTo{
        public boolean selected {get;set;}
        public void setSelected(Boolean isSelected){
            selected = isSelected;
        }
        public Bill_To__c billTo {get;set;}
        public wrapBillTo(Bill_To__c billTo,Boolean alreadySelected){
            this.selected = alreadySelected;
            this.billTo = billTo;
        }
    }
}