force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditLimit__c/CreditLimit__c.object-meta.xml
<CustomObject>
    <label>Credit Limit</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Credit Limit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Limits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditLimit__c/fields/CommercialAccount__c.field-meta.xml
<CustomField>
    <fullName>CommercialAccount__c</fullName>
    <label>Commercial Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CommercialAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Limits</relationshipLabel>
    <relationshipName>Credit_Limits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Integration_profile__c/Integration_profile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All list of Profiles for OOTB config &amp; customization</description>
    <label>Integration profile</label>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/CreditLimit__c.field-meta.xml
<CustomField>
    <fullName>CreditLimit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Limit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Commercial_Account__c</field>
            <operation>equals</operation>
            <valueField>CreditLimit__c.CommercialAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CreditLimit__c</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AVX_CreditLimitTriggerHelper_tst.cls
@isTest
public class AVX_CreditLimitTriggerHelper_tst {
    @TestSetup
    static void makeData(){
        User objSupervisorUser = AVX_DataGenerator_cls.createUser('Misa');
        insert objSupervisorUser;

        Integration_profile__c objCustomSettings = AVX_DataGenerator_cls.createCustomSettings(true);
        insert objCustomSettings;

        Account objGlobalAcc = AVX_DataGenerator_cls.createGlobalAccount('GlobalAcc');
        insert objGlobalAcc;

        Account objCommercialAcc = AVX_DataGenerator_cls.createCommercialAccount('CommercialAcc', objGlobalAcc);
        insert objCommercialAcc;

        Account objCommercialAcc2 = AVX_DataGenerator_cls.createCommercialAccount('CommercialAcc2', objGlobalAcc);
        insert objCommercialAcc2;

        Account objPayerAcc = AVX_DataGenerator_cls.createPayerAccount('PayerAcc', objCommercialAcc);
        insert objPayerAcc;

        Contact objContact = AVX_DataGenerator_cls.createContact('El', objGlobalAcc, 'misa@el.com');
        insert objContact;

        Bill_To__c objBillTo = AVX_DataGenerator_cls.createBillTo('BillTo1', objPayerAcc, objCommercialAcc);
        insert objBillTo;

        Ship_To__c objShipTo = AVX_DataGenerator_cls.createShipTo('ShipTo1', objPayerAcc, objBillTo);
        insert objShipTo; 

        CreditLimit__c objCreditLimit = AVX_DataGenerator_cls.createCreditLimit(objCommercialAcc);
        insert objCreditLimit;

        CreditLimit__c objCreditLimit2 = AVX_DataGenerator_cls.createCreditLimit(objCommercialAcc2);
        objCreditLimit2.IsActive__c = false;
        insert objCreditLimit2;
    }

    @isTest
    public static void relateShipToAndCreditLimitInsert(){
        CreditLimit__c objCreditLimit = [SELECT Id FROM CreditLimit__c WHERE CommercialAccount__r.Name = 'CommercialAcc'];
        System.assert(objCreditLimit != null);

        Ship_To__c objShipTo = [SELECT Id FROM Ship_To__c WHERE Name = 'ShipTo1'];
        System.assert(objShipTo != null);
    }

    @isTest
    public static void relateShipToAndCreditLimitUpdate(){
        User objUser = [SELECT Id FROM User WHERE FirstName = 'Misa'];
        System.assert(objUser != null);

        CreditLimit__c objCreditLimit = [SELECT Id, IsActive__c FROM CreditLimit__c WHERE CommercialAccount__r.Name = 'CommercialAcc2'];
        System.assert(objCreditLimit != null);

        Ship_To__c objShipTo = [SELECT Id FROM Ship_To__c WHERE Name = 'ShipTo1'];
        System.assert(objShipTo != null);

        Test.startTest();
        System.runAs(objUser){
            objCreditLimit.IsActive__c = true;
            update objCreditLimit;
        }
        Test.stopTest();
    }
}