force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Ship_To__c/Quote_Ship_To__c.object-meta.xml
<CustomObject>
    <label>Quote Ship To</label>
    <nameField>
        <displayFormat>QS-{00000}</displayFormat>
        <label>Quote Ship To Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Ship_To__c/fields/PROS_Quote__c.field-meta.xml
<CustomField>
    <fullName>PROS_Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>CameleonCPQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Ship To&#39;s</relationshipLabel>
    <relationshipName>Quote_Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quote Ship To&#39;s</relationshipLabel>
    <relationshipName>Quote_Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <externalId>true</externalId>
    <label>ERP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Legacy_System__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System__c</fullName>
    <label>Legacy System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XLGO</fullName>
            </value>
            <value>
                <fullName>XLDM</fullName>
            </value>
            <value>
                <fullName>CBS</fullName>
            </value>
            <value>
                <fullName>CTCM</fullName>
            </value>
            <value>
                <fullName>PROTEAN</fullName>
            </value>
            <value>
                <fullName>FIVE STAR</fullName>
            </value>
            <value>
                <fullName>CFD</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>CVAP EGG</fullName>
            </value>
            <value>
                <fullName>JDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Bill_To__c</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CPG_QuoteShipTo_TriggerHelper.cls
/**
Class Name: CPG_QuoteShipTo_TriggerHelper
Created Date: Jan-04-2017
Created By: Cognizant
This class is  helper class for Quote Ship To Trigger.
**/
public class CPG_QuoteShipTo_TriggerHelper{
//Method to set up Ship To/Sold To on Quote
public static void updateSoldToShipTo(list<Quote_ship_to__c> lstQuoteShipTo){
    set<id> setQuotes = new set<id>();
    map<id,string> mapQShipTo = new map<id, string>();
    map<id,string> mapQShipToDesc = new map<id, string>();
    map<id,string> mapQSoldTo = new map<id, string>();
    list<CameleonCPQ__Quote__c> lstQuotes = new list<CameleonCPQ__Quote__c>();
    
    //Get the Quotes for querying updated list of Quote Ship To's
    for(Quote_ship_to__c qs:lstQuoteShipTo){
        setQuotes.add(qs.PROS_Quote__c);
    }
    if(!setQuotes.isEmpty()){
        for(Quote_ship_to__c qs:[select PROS_Quote__c,ship_to__r.Description__c,ship_to__r.legacy_id__c,ship_to__r.legacy_system__c, ship_to__r.erp_Number__c , ship_to__r.sold_to__r.erp_Number__c from quote_ship_to__c where PROS_Quote__c in:setQuotes]){
            if(!mapQShipTo.isEmpty() && mapQShipTo.containsKey(qs.pros_quote__c)){
                string shipTos = mapQShipTo.get(qs.pros_quote__c)+';'+qs.ship_to__r.erp_number__c+'|'+qs.ship_to__r.legacy_system__c;
                mapQShipTo.put(qs.pros_quote__c,shipTos);
                
                string shipTosDesc = mapQShipToDesc.get(qs.pros_quote__c)+';'+qs.ship_to__r.Description__c;
                mapQShipToDesc.put(qs.pros_quote__c,shipTosDesc);
                
                string soldTos = mapQSoldTo.get(qs.pros_quote__c)+';'+qs.ship_to__r.sold_to__r.erp_Number__c;
                mapQSoldTo.put(qs.pros_quote__c,soldTos);               
            }
            else{
                string shipTos = qs.ship_to__r.erp_number__c+'|'+qs.ship_to__r.legacy_system__c;
                mapQShipTo.put(qs.pros_quote__c,shipTos);
                string shipTosDesc = qs.ship_to__r.description__c;
                mapQShipToDesc.put(qs.pros_quote__c,shipTosDesc);
                
                string soldTos = qs.ship_to__r.sold_to__r.erp_Number__c;
                mapQSoldTo.put(qs.pros_quote__c,soldTos);     
            }    
        }    
    } 
    
    //Update Quotes with added/deleted Ship To/Sold To list
    if(!setQuotes.isEmpty()){
        for(id qId :setQuotes){
            if(!mapQShipTo.isEmpty() && mapQShipTo.containsKey(qId)){
                lstQuotes.add(new CameleonCPQ__Quote__c(id = qId, Ship_To_List__c = mapQShipTo.get(qId), Ship_To_Description_List__c = mapQShipToDesc.get(qId), Sold_To_List__c = mapQSoldTo.get(qId)));    
            }
            else{
                lstQuotes.add(new CameleonCPQ__Quote__c(id = qId, Ship_To_List__c = null, Ship_To_Description_List__c=null,Sold_To_List__c = null)); 
            }
        }
        //UPdate Quotes with new Ship To/Sold To list
        database.update(lstQuotes, false);
    }
    
}
}