force-app/main/default/objects/Bill_To__c/Bill_To__c.object-meta.xml
<CustomObject>
    <label>Bill To</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_To__c/fields/Commercial_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Global_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_To__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill To&#39;s</relationshipLabel>
    <relationshipName>Bill_To_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CPG_Bill_To_TriggerHandler.cls
/**
Class Name: CPG_Bill_To_TriggerHandler
Created Date: Nov-07-2017
Created By: Cognizant
This class is  helper class for updating Commercial Account details for Bill To data.
**/
public class CPG_Bill_To_TriggerHandler{
//Method to set up Commercial Accounts
public static void setupBillToCommercialAccounts(){
    map<id,id> mapPayerCommercial = new map<id,id>();
    map<id,id> mapPayerGlobal = new map<id,id>();
    set<id> setPayers= new set<id>();
    if(Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate)){
        for(Bill_To__c sh:(list<Bill_to__c>)Trigger.New){
            if(Trigger.isInsert){
               setPayers.add(sh.Payer__c);             
            }
            else if(Trigger.isUpdate && sh.Payer__c!=((Bill_to__c)Trigger.oldMap.get(sh.id)).Payer__c){
                setPayers.add(sh.Payer__c);   
            }
        }            
    }
    if(!setPayers.isEmpty()){
        for(Account payer:[select parentid,id,parent.parentid from Account where id in:setPayers]){
            mapPayerCommercial.put(payer.id,payer.parentid);
            mapPayerGlobal.put(payer.id,payer.parent.parentid);
        }
    }
    if(!mapPayerCommercial.isempty()){
        for(Bill_To__c sh:(list<Bill_to__c>)Trigger.New){
            if(mapPayerCommercial.containsKey(sh.Payer__c)){
                sh.Commercial_Account__c= mapPayerCommercial.get(sh.Payer__c);
                sh.global_Account__c = mapPayerGlobal.get(sh.Payer__c);
                
            }
        }
    }
}

}