force-app/main/default/objects/SalesScript__c/SalesScript__c.object-meta.xml
<CustomObject>
    <label>Sales Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesScript__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesScript__c/fields/CountyCode__c.field-meta.xml
<CustomField>
    <fullName>CountyCode__c</fullName>
    <label>County Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesScript__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesScript__c/fields/TelesalesScript__c.field-meta.xml
<CustomField>
    <fullName>TelesalesScript__c</fullName>
    <label>Telesales Script</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/CountyCode__c.field-meta.xml
<CustomField>
    <fullName>CountyCode__c</fullName>
    <label>County Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AVX_SalesScript_ctr.cls
/**************************************************************************************************************
* Avanxo Brasil
* @author           Ismael Sanchez (isanchez@avanxo.com)
* Project:          CPLA - EXODUS Project
* Description:      Class used to show the sales script related a client
*
* Changes (Version)
* -------------------------------------
*           No.     Date            Author                      Description     
*           -----   ----------      --------------------        ---------------   
* @version   1.0    2020-03-05      Ismael Sanchez              class created 
*************************************************************************************************************/
public with sharing class AVX_SalesScript_ctr {
    public AVX_SalesScript_ctr() {

    }

    @AuraEnabled(cacheable=true)
    public static Ship_To__c getShipToByTask( String idTask){
        Ship_To__c shipTo = new Ship_To__c();
        List<Task> lstTasks = [Select Id, ShipTo__c from Task where id=:idTask ];
        if(!lstTasks.isEmpty()){
            Id idShipTo = lstTasks[0].ShipTo__c;
            List<Ship_To__c> lstShipTos = [Select Country__c, CountyCode__c from  Ship_To__c where id =:idShipTo];
            if(!lstShipTos.isEmpty()){
                shipTo = lstShipTos[0];
            }
        }
        return shipTo;
    }

    @AuraEnabled(cacheable=true)
    public static List<SalesScript__c> getSalesScriptByCountry( String country){
        List<SalesScript__c> lstSripts = new List<SalesScript__c>();
        String status = 'Active';
        String strEmpty = '';
        lstSripts = Database.query(String.escapeSingleQuotes('Select Name,Country__c,CountyCode__c,TelesalesScript__c from  SalesScript__c  where  Status__c=:status ORDER BY CountyCode__c ASC NULLS FIRST'));
        return lstSripts;
    }

}