force-app/main/default/objects/Product_Collection__mdt/Product_Collection__mdt.object-meta.xml
<CustomObject>
    <label>Product Collection</label>
    <pluralLabel>Product Collections</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Collection__mdt/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Egg</fullName>
                <default>true</default>
                <label>Egg</label>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Boxed Beef/Ground Beef</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Collection__mdt/fields/Pricer__c.field-meta.xml
<CustomField>
    <fullName>Pricer__c</fullName>
    <description>Pricer</description>
    <label>Pricer</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <description>Used for Avenger Protein</description>
    <label>New Product Collection Form</label>
    <nameField>
        <label>Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Product Collection Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Request__c/fields/Pricing_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Due_Date__c</fullName>
    <description>Pricing Due Date</description>
    <label>Pricing Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Pricing_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Notification_Date__c</fullName>
    <description>Pricing Notification Date</description>
    <label>Date Price Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Pricing_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Timeframe__c</fullName>
    <label>Pricing Timeframe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Product Collection Forms</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Sent_to_Pricer__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Pricer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sent to Pricer</description>
    <label>Sent to Pricer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Accepted by BM</fullName>
            </value>
            <value>
                <fullName>Rejected by BM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Protein_SendToPricerController.cls
/*
Author: Mahesh C
Description : This method is written to send Email To Pricer based on Opportunity Type
Method Name : updateEmailMessageBeforeInsert      

*/

public with sharing class Protein_SendToPricerController {
    
    @AuraEnabled
    public static String sendEmail(Id prodColId){
        string validateMsg='';
        Boolean isSentToPricer=false;
        Boolean isFieldCheck=false;
        set<Id> oppId=new set<Id>();
        List<Id> pROwner=new List<Id>();
        
        List<Product_Request__c> prodReq=[select id,Name,CreatedById ,Related_Opportunity__c,Sent_to_Pricer__c,Status__c,Pricing_Due_Date__c,Pricing_Timeframe__c,Pricing_Notification_Date__c from Product_Request__c where Id=:prodColId];
        system.debug('ProdReq++++'+prodReq);
        
        for(Product_Request__c pr:ProdReq){
            oppId.add(prodReq[0].Related_Opportunity__c);
            pROwner.add(pr.CreatedById);
            system.debug('oppId Value+++'+oppId);
            //validate the mandatory fields
            isSentToPricer = Protein_SendToPricerHelper.validateSendToPricer(pr,isSentToPricer);
            system.debug('isSentToPricer++'+isSentToPricer);
            isFieldCheck = Protein_SendToPricerHelper.validateFieldCheckOne(pr,isFieldCheck);
            system.debug('isFieldCheck++'+isFieldCheck);
                       
        }
        
        List<Opportunity> oppList=new List<Opportunity>();
        if(oppId!=Null){
            oppList= [select id,Name,RecordType.Name from Opportunity where id IN: oppId];
            System.debug('oppList++'+oppList);
        }
        
        List<Product_Collection__mdt> prodColectionMappingList=[select id,Opportunity_Type__c,Pricer__c From Product_Collection__mdt];
        system.debug('ProdColectionMapping++++'+prodColectionMappingList);
 //      EmailTemplate et = [Select Id from EmailTemplate where Name = 'Email to Pricing Team'];
        List<string> mdtString=new List<string>();               
        boolean flag;
        Map<String,String> oppmdtRecType = new Map<String,String>();
        
        for(Opportunity opp:oppList){    
        
            oppmdtRecType.clear();
            flag = false;
            for(Product_Collection__mdt mdt:ProdColectionMappingList){
                
                if(isSentToPricer == true){
                   validateMsg = 'Checkbox Checked';  
                   system.debug('%%%checkbox check='+validateMsg);                  
                }
                else if(Opp.RecordType.Name == mdt.Opportunity_Type__c){
                    mdtString.add(mdt.Pricer__c);                
                    flag = true;  
                    oppmdtRecType.put(Opp.RecordType.Name, mdt.Opportunity_Type__c);         
                }               
            }
             validateMsg = validateOppRecType(flag,oppmdtRecType,validateMsg,isFieldCheck,isSentToPricer,mdtString,pROwner,opp,prodReq);
             system.debug('%%%checkbox cjeck222='+validateMsg); 
        } 
            
        return validateMsg;
    } 
    private static string validateOppRecType(Boolean flag,Map<String,String> oppmdtRecType,string validateMsg,Boolean isFieldCheck,Boolean isSentToPricer,List<string> mdtString,List<Id> pROwner,Opportunity opp,List<Product_Request__c> prodReq)
    {
        EmailTemplate et = [Select Id from EmailTemplate where Name = 'Email to Pricer' limit 1];
        if(!flag && oppmdtRecType.get(Opp.RecordType.Name) == null && ValidateMsg != 'Checkbox Checked'){                    
            ValidateMsg='Record Type not matched';                    
        }
        else if(isFieldCheck == true && flag == true){
                    
                    validateMsg='Pricing date blank';                   
        }
        else if(isvalidCheck(isFieldCheck,isSentToPricer,validateMsg))
        {
                List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();    
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(MdtString);
            mail.setWhatId(prodReq[0].id);
                mail.setTargetObjectId(pROwner[0]);
                mail.setSaveAsActivity(false);
                mail.setBccSender(false);
              //  mail.setHtmlBody('Hi  <br/><br/>New Product Collection Record is created<br/><br/> Thanks <br/>');
                mail.setTemplateId(et.id);
                mails.add(mail);
                Messaging.SendEmailResult[] results = Messaging.sendEmail(mails);
                system.debug('results++'+results);
                
                if(results[0].success){
                    updateProdReqData(ProdReq);
                    system.debug('ProdReq Update Check'+ProdReq);
                    validateMsg= 'Success Email';
                }
                else{
                    validateMsg= 'Email failed';
                }
         system.debug('%%%checkbox cjeck33='+validateMsg);                       
        }
        system.debug('%%%checkbox cjeck44='+validateMsg); 
        return validateMsg;
    } 

    private static boolean isvalidCheck(boolean isFieldCheck, boolean isSentToPricer, string validateMsg){
    
        return (isFieldCheck == false && isSentToPricer == false && validateMsg != 'Checkbox Checked');
    
    }

    public static void updateProdReqData(List<Product_Request__c> prodReq){
        List<Product_Request__c> updatePRList = new List<Product_Request__c>();
        
        for(Product_Request__c pr : prodReq)
        {
            pr.Sent_to_Pricer__c=True;
            pr.Pricing_Notification_Date__c=system.today();   
            updatePRList.add(pr);
        }
        try{
            if(!updatePRList.isEmpty())
            {
                update updatePRList;
            }
        }catch(exception e){
            system.debug('exception::'+e);    
        }
    }
}