force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/CS_Ship_To_Contact_Relation__c.object-meta.xml
<CustomObject>
    <description>This is the junction object to relate contact to ship to. The relation between this object and contact &amp; Ship To is maintained as lookup relation so that the record in this object can be edited.</description>
    <label>Ship To Contact Relation</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Ship To Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ship To Contact Relation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/fields/CS_Contact__c.field-meta.xml
<CustomField>
    <fullName>CS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact related to same commercial account as that of Ship To.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_Contact_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/fields/CS_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>CS_Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship To related to same commercial account as that of contact.</description>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Ship_To_Contact_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CS_Ship_To_Contact_Relation__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&#39;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ship To&#39;s</relationshipLabel>
    <relationshipName>Ship_To_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AVX_ShipToContactRelationTgrHelper_cls.cls
/**
**************************************************************************************************************
* @company          Avanxo Brasil
* @author           Igor Novaes href=<igor.novaes@globant.com>
* @project          EXODUS - CPLA Cargill
* @name             AVX_CreditLimit_tgr
* @description      Helper for the trigger AVX_ShipToContactRelation_tgr
* @dependencies     none
* @changes (Version)
* --------   ---   ----------   ---------------------------   ------------------------------------------------
*            No.   Date         Author                        Description
* --------   ---   ----------   ---------------------------   ------------------------------------------------
* @version   1.0   2020-02-04   Igor Novaes.                  Initial version.
**************************************************************************************************************
**/

public class AVX_ShipToContactRelationTgrHelper_cls {

    public static void relateContactPrimaryContact(List<CS_Ship_To_Contact_Relation__c> lstContext) {

        Map<Id,Id> mapContactToShipTo = new Map<Id,Id>();
        for(CS_Ship_To_Contact_Relation__c objContactToShipTo : lstContext){
            if(objContactToShipTo.PrimaryContact__c){
                mapContactToShipTo.put(objContactToShipTo.CS_Ship_To__c,objContactToShipTo.CS_Contact__c);
            }
        }

        List<Ship_To__c> lstShipTo = [SELECT Id, PrimaryContact__c FROM Ship_To__c WHERE Id IN :mapContactToShipTo.keySet()];
        
        if(lstShipTo != null && !lstShipTo.isEmpty()){
            List<Ship_To__c> lShipToUpdt = new List<Ship_To__c>();
            for(Ship_To__c objShipTo : lstShipTo){
                if(objShipTo.PrimaryContact__c != mapContactToShipTo.get(objShipTo.Id)){
                    objShipTo.PrimaryContact__c = mapContactToShipTo.get(objShipTo.Id);
                    lShipToUpdt.add(objShipTo);
                }
            }

            if(lShipToUpdt != null && !lShipToUpdt.isEmpty()){
                update lShipToUpdt;
            }
        }
    }    
}