force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Cargill Product Production Plants</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Request_Fulfillment__c/Sample_Request_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Sample Fulfillment</label>
    <nameField>
        <displayFormat>SRF-{000000}</displayFormat>
        <label>Sample Fulfillment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SampleRequest__c/SampleRequest__c.object-meta.xml
<CustomObject>
    <description>Sample Request (CVAP)</description>
    <label>Sample</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sample Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SampleRequest__c/fields/CFNA_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>CFNA_Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cargill Beef</fullName>
            </value>
            <value>
                <fullName>Case Ready</fullName>
            </value>
            <value>
                <fullName>Cocoa &amp; Chocolate</fullName>
            </value>
            <value>
                <fullName>CVAP-Beef (Burgers)</fullName>
            </value>
            <value>
                <fullName>CVAP-Poultry (Eggs)</fullName>
            </value>
            <value>
                <fullName>Foodservice Oils</fullName>
            </value>
            <value>
                <fullName>Salt</fullName>
            </value>
            <value>
                <fullName>Sugar</fullName>
            </value>
            <value>
                <fullName>Truvia</fullName>
            </value>
            <value>
                <fullName>Turkey &amp; Cooked Meats</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SampleRequestProduct__c/SampleRequestProduct__c.object-meta.xml
<CustomObject>
    <label>Sample Product</label>
    <nameField>
        <displayFormat>SRPN-{000000}</displayFormat>
        <label>Sample Product #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SampleRequestProduct__c/fields/CFNA_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>CFNA_Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cargill Beef</fullName>
            </value>
            <value>
                <fullName>Case Ready</fullName>
            </value>
            <value>
                <fullName>Cocoa &amp; Chocolate</fullName>
            </value>
            <value>
                <fullName>CVAP-Beef (Burgers)</fullName>
            </value>
            <value>
                <fullName>CVAP-Poultry (Eggs)</fullName>
            </value>
            <value>
                <fullName>Foodservice Oils</fullName>
            </value>
            <value>
                <fullName>Salt</fullName>
            </value>
            <value>
                <fullName>Sugar</fullName>
            </value>
            <value>
                <fullName>Truvia</fullName>
            </value>
            <value>
                <fullName>Turkey &amp; Cooked Meats</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SampleRequestProduct__c/fields/CFNA_Type__c.field-meta.xml
<CustomField>
    <fullName>CFNA_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CFNA_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 LB Bag</fullName>
                <default>true</default>
                <label>1 LB Bag</label>
            </value>
            <value>
                <fullName>25 LB Bag</fullName>
            </value>
            <value>
                <fullName>2LB Bag</fullName>
            </value>
            <value>
                <fullName>50LB Bag</fullName>
            </value>
            <value>
                <fullName>5 LBS</fullName>
            </value>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Can</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Chub</fullName>
            </value>
            <value>
                <fullName>JIB</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
            <value>
                <fullName>LBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Piece</fullName>
            </value>
            <value>
                <fullName>8 OZ JAR</fullName>
            </value>
            <value>
                <fullName>1 Tray</fullName>
            </value>
            <value>
                <fullName>Crumbles</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SampleRequestProduct__c/fields/Sample_Request_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Sample_Request_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Request Fulfillment</label>
    <referenceTo>Sample_Request_Fulfillment__c</referenceTo>
    <relationshipLabel>Sample Request Products</relationshipLabel>
    <relationshipName>Sample_Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SampleRequestProduct__c/fields/SampleRequest__c.field-meta.xml
<CustomField>
    <fullName>SampleRequest__c</fullName>
    <label>Sample Request</label>
    <referenceTo>SampleRequest__c</referenceTo>
    <relationshipLabel>Sample Request Products</relationshipLabel>
    <relationshipName>Sample_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Protein_SampleRequestController_Test.cls
@isTest(seeAlldata=false)
public class Protein_SampleRequestController_Test {
    static testmethod void test1() {
        Account acc = Protein_TestDataFactory.createAccountRecord('Test Account', 'Commercial Account', 'Retail');
        System.assertEquals('Test Account' , acc.Name);
        //Product2 Prd2 = Protein_TestDataFactory.createProduct('Heritage');
        //Plant__c plnt= Protein_TestDataFactory.createPlant('Walmart INC');
        SampleRequest__c sRReq = Protein_TestDataFactory.SampleRequestRec(acc.Id, 'salt', 'competitive Cutting', 'draft', System.today(), System.today()+30,'foodservice', 'mahesh', 'test@gmail.com', 'yes');
        SampleRequestProduct__c sRProd = Protein_TestDataFactory.sampleRequestPrd(sRReq.Id,'prodDesc', 'productCode', 12);
        system.debug('%%%SRProd%%%'+sRProd);
        Sample_Request_Fulfillment__c sRFul = Protein_TestDataFactory.sampleRequestFul(sRReq.Id,'walmart');
        List<String> sRPList=new List<String>();
        sRPList.add(sRProd.Id);
        Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper prodSelUnsel1 = Protein_TestDataFactory.createProductSelectUnselectWrapper(sRProd, SRReq, 'fulfilled');
        List<Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper> lstProdSelUnsel1 = new List<Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper>();
        lstProdSelUnsel1.add(prodSelUnsel1);
        Protein_SampleRequestFulfillmentCtlr.saveSampleRequestDetails(JSON.serialize(lstProdSelUnsel1),sRFul.Id);
        Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper prodSelUnsel2 = Protein_TestDataFactory.createProductSelectUnselectWrapper(sRProd, sRReq, '--None--');
        List<Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper> lstProdSelUnsel2 = new List<Protein_SampleRequestFulfillmentCtlr.ProductSelectUnselectWrapper>();
        lstProdSelUnsel2.add(prodSelUnsel2);
        Protein_SampleRequestFulfillmentCtlr.saveSampleRequestDetails(JSON.serialize(lstProdSelUnsel2),sRFul.Id);
        Protein_SampleRequestController.populateCFNASampleRequestFormData(sRReq.id);
        Protein_SampleRequestController.fetchSampleRequestInfoOnExcel(sRReq.id);
        Protein_SampleRequestController.fetchSampleProductInfoOnExcel(sRReq.id);
        Protein_SampleRequestController.checkSampleProductData(sRReq.id);
        Protein_SampleRequestFulfillmentCtlr.getSampleRequestProducts(sRReq.id);
        Protein_SampleRequestFulfillmentCtlr.getSRP_BUs();
        Protein_SampleRequestFulfillmentCtlr.getRemovedProductDetails(sRPList,sRFul.Id); 
        Protein_SampleRequestFulfillmentCtlr.getProductWrapperList(sRFul.Id);
        Protein_SampleRequestProductController.fetchLookUpValues('test', 'Account'); 
        Protein_SampleRequestFulfillmentCtlr.getSelectedProductList(sRPList,sRFul.Id );
        Protein_SampleRequestProductController.getSampleDetails(sRReq.id);
        Protein_SampleRequestProductController.getSampleRequestProductsOfASample(sRReq.id);
        Protein_SampleRequestProductController.deleteSRProduct(sRProd.Id);
        // Convert to schema.sObjectType and then create an instance of that type
        Sobject genericObject = Schema.getGlobalDescribe().get('SampleRequestProduct__c').newSObject();   
        Protein_SampleRequestProductController.getDependentMap(genericObject, 'CFNA_Business_Unit__c', 'CFNA_Type__c');  //Harshitha
        Protein_SampleRequestProductController.decimalToBinary(2);
        Protein_SampleRequestProductController.base64ToBits('test');
        SampleRequestProduct__c sRProd1 = Protein_TestDataFactory.sampleRequestPrd(sRReq.Id,'prodDesc', 'productCode', 12);
        Protein_SampleRequestProductController.deleteRecord(sRProd1.Id);
        Protein_SampleRequestFulfillmentCtlr.getProductWrapperList(sRFul.Id);
    }
    
    public static testMethod void upsertSRProductsTest() {
        //Protein_SampleRequestController.SRProductWrapperOfASample prodWrapper = new Protein_SampleRequestController.SRProductWrapperOfASample();
        Account acc = Protein_TestDataFactory.createAccountRecord('Test Account', 'commercial Account', 'retail');
        System.assertEquals('Test Account' , acc.Name);
        //Product2 Prd2 = Protein_TestDataFactory.createProduct('test Product');
        SampleRequest__c sReq = Protein_TestDataFactory.SampleRequestRec(acc.Id, 'salt', 'competitive Cutting',  'draft', System.today(), System.today()+30,'foodservice', 'mahesh', 'test@gmail.com', 'no');
        SampleRequestProduct__c sRProd = Protein_TestDataFactory.sampleRequestPrd(SReq.Id,'prodDesc', 'productCode', 12);
        SampleRequestProduct__c sRProd1 = Protein_TestDataFactory.sampleRequestPrd(SReq.Id,'prodDesc', 'productCode', 12);
        List<Protein_SampleRequestProductController.SRProductWrapperOfASample> lstSRPWrapper = Protein_SampleRequestProductController.getSampleRequestProductsOfASample(sReq.Id);
        lstSRPWrapper[0].isNew = true;
        lstSRPWrapper[1].isNew = false;
        Protein_SampleRequestProductController.upsertSRProducts(sReq.id, JSON.serialize(lstSRPWrapper), 'salt');
    }
    
    public static testMethod void sendSampleRequestTest() {
        Account acc = Protein_TestDataFactory.createAccountRecord('Test Account', 'Commercial Account', 'Retail');
        System.assertEquals('Test Account' , acc.Name);
        SampleRequest__c sRReq1 = Protein_TestDataFactory.SampleRequestRec(acc.Id, 'salt', 'competitive Cutting', 'draft', System.today(), System.today()+30,'foodservice', 'mahesh', 'test@gmail.com', 'yes');
        Response getSampleRequestWrapperList1 = Protein_SampleRequestController.getSampleRequestWrapperList(sRReq1.id);
        List<Protein_SampleRequestController.sampleRequestWrapper> wrapList1 = (List<Protein_SampleRequestController.sampleRequestWrapper>)getSampleRequestWrapperList1.data;
        Protein_SampleRequestController.sendSampleRequest(sRReq1.id, JSON.serialize(wrapList1[0]), 'TEST');
        
        SampleRequest__c sRReq2 = Protein_TestDataFactory.SampleRequestRec(acc.Id, 'salt', 'competitive Cutting', 'draft', System.today(), System.today()+30,'retail', 'mahesh', null, 'no');
        Response getSampleRequestWrapperList2 = Protein_SampleRequestController.getSampleRequestWrapperList(sRReq2.id);
        List<Protein_SampleRequestController.sampleRequestWrapper> wrapList2 = (List<Protein_SampleRequestController.sampleRequestWrapper>)getSampleRequestWrapperList2.data;
        Protein_SampleRequestController.sendSampleRequest(sRReq2.id, JSON.serialize(wrapList2[0]), 'TEST');
        Protein_SampleRequestController.populateCFNASampleRequestFormData(sRReq2.id);
        
        SampleRequest__c sRReq3 = Protein_TestDataFactory.SampleRequestRec(acc.Id, 'salt', 'competitive Cutting', 'draft', System.today(), System.today()+30,'ingredient', 'mahesh', null, 'no');
        Response getSampleRequestWrapperList3 = Protein_SampleRequestController.getSampleRequestWrapperList(sRReq3.id);
        List<Protein_SampleRequestController.sampleRequestWrapper> wrapList3 = (List<Protein_SampleRequestController.sampleRequestWrapper>)getSampleRequestWrapperList3.data;
        Protein_SampleRequestController.sendSampleRequest(sRReq3.id, JSON.serialize(wrapList3[0]), 'TEST');
        Protein_SampleRequestController.populateCFNASampleRequestFormData(sRReq3.id);
    }
    
}